### ISSUE TITLE
Unknown versions of browsers

### ISSUE THREAD

**Issue by iamvdo** [ai/browserslist#10]
Some versions are not in `data` and autoprefixer throws error `Unknown version N of NAME`.

For example, for `ios_saf`, there are only:
```javascript
versions: [ '3.2', '4.1', '4.3', '5.1', '6.1', '7.1', '8', '8.1' ]
```

Misses version 4, 4.2, 5, 6 and 7.

**Comment by ai** [comment]
This is how Can I Use data looks like. They pack some verions into one pack like `6-6.1`.

**Comment by ai** [comment]
Maybe we can remember that we unpack `6-6.1` to `6.1` and add alias for `6`. But I have no time in next 2 week. Can I ask you to send a PR?

**Comment by iamvdo** [comment]
What about "aliases" versions ? Should they appear in `released` too ?

**Comment by ai** [comment]
What is `released`?

**Comment by iamvdo** [comment]
`released` refers to `browserslist.data[name].released`, but I supposed aliases versions should not appear in.

Dumb question, what about versions named `8` and / or `8.0` ?

**Comment by ai** [comment]
OK, I made Browserslist version detect smarter:

* Browserslist understand `7.0` and `7.1` for Can I Use `7.0-7.1`: 54d7503e738a653fb717ce440b7c42a160651027
`8.0` is now alias for `8` and `7` is alias for `7.0`: d5b19f295e15b00682b137e8454fad6abdd183c2

**Comment by ai** [comment]
Released in 0.1.3 version

**Comment by iamvdo** [comment]
OK great. I forked repo and prepared PR for tomorrow. Sorry if I was too slow...

**Comment by ai** [comment]
Oops :). No problem, I decide to fix it fast to make fixed 0.1.3 as dependency of Autoprefixer 5.1 release.

**Comment by iamvdo** [comment]
You're the boss ! :)

**Comment by iamvdo** [comment]
There is a problem using Autoprefixer. It seems that prefixing doesn't occur, because `autoprefixer.data.browsers` uses `./data/browsers.js` file instead of `browserslist` package, or am I missing something ?

**Comment by ai** [comment]
Yeap, but Browserslist should normalize output for `./data/browsers.js`.

**Comment by ai** [comment]
Hm. I will looks inside

**Comment by ai** [comment]
I think I fix problem. Can you check latest master of `autoprefixer-core`?

**Comment by iamvdo** [comment]
Seems to work ! :+1:
