### ISSUE TITLE
Feature request: Target by WEBGL compatibility

### ISSUE THREAD

**Issue by yvele** [ai/browserslist#103]
Awesome project, I'm using it within [babel-preset-env](https://github.com/babel/babel-preset-env)

Is it conceivable to add a WEBGL query? For those who builds games, etc.. 

PS: Related to @AndyBarron request https://github.com/ai/browserslist/issues/91#issuecomment-267815631

-----

Unrelated:
  - Don't you should add `yarn.lock` in `.gitignore` and remove [it](https://github.com/ai/browserslist/blob/master/yarn.lock) from SCM?
  - About [files field](https://docs.npmjs.com/files/package.json#files) over `.npmignore` http://stackoverflow.com/a/37421736/1480391

**Comment by ai** [comment]
I thought too about `yarn.lock` ignoring, but Yarn team have different opinion https://yarnpkg.com/en/docs/yarn-lock#toc-check-into-source-control

**Comment by ai** [comment]
I tottaly agree that we need node.js and other desktop non-browsers things in Browserlist. But I need some real use cases and implementation examples from Babel team.

How do you think we should add WebGL query? WebGL is a feature or engine?

Feature should be added to [`caniuse-api`](https://github.com/nyalab/caniuse-api). This library to select browsers supported in some project.

**Comment by yvele** [comment]
@ai Hum ok... interesting about yarn.lock, thank you for the info

**Comment by yvele** [comment]
@ai I understand... I could just use [caniuse-api](https://github.com/nyalab/caniuse-api) to build a [browserslist](https://github.com/ai/browserslist) query.. 

But it's quite confusing, both [browserslist](https://github.com/ai/browserslist) (`>1%`, etc..) and [caniuse-api](https://github.com/nyalab/caniuse-api) allows to make a "query".. I can't really understand what are the separation of concerns here. You seem to say that feature/engine is the separation..  Why? It doesn't look user friendly..

**Comment by ai** [comment]
@yvele it could be awesome, but it will dramatically increase Browserslist size and kill any client-side usage.
