### ISSUE TITLE
add example of use with autoprefixer to README.md?

### ISSUE THREAD

**Issue by Pomax** [ai/browserslist#109]
Would it be possible to show in the README.md how to actually use this in combination with something like autoprefixer/post-css/etc, so that it's clear how to chain the output of browserlist with another cli?

**Comment by ai** [comment]
@Pomax why this example in first section of docs are bad for you?

```
In package.json:

{
  "private": true,
  "dependencies": {
    "autoprefixer": "^6.5.4"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}
```

**Comment by Pomax** [comment]
They're not complete: this doesn't tell me how to actually use browserlist with something through, for instance, an npm script that I can invoke with `npm run makecompatible`. The example show only shows me that autoprefixer is installed, and that browserlist has a config, but it does not mention how to invoke browserlist, or how to chain it into another tool.

**Comment by ai** [comment]
You don't need to invoke Browserslist. Autoprefixer will load Browserslist config automatically.

**Comment by Pomax** [comment]
okay, but you can't invoke autoprefixer on its own as a CLI utility (it needs post-css according to its own readme), so can you shown an npm script in that minimal example of how its used? Would this work?
```
{
  "private": true,
  "dependencies": {
    "autoprefixer": "^6.5.4",
    "post-css": "^...."
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ],
  "scripts": {
    "prefix": "postcss --use autoprefixer *.css -d build/autoprefixer css/main.css"
  }
}
```

**Comment by ai** [comment]
@Pomax this code should work

**Comment by ai** [comment]
There is so many way to run Autoprefixer (Gulp, webpack, CLI). Also Browserslist is used in Stylelint, cssnext, Babel. It will be so hard to describe every example :).

But you can send PR if you know a solution.

**Comment by Pomax** [comment]
Cool, instead of closing the issue, can you please update the README to mention that, and then close the issue? That way other people won't be as confused as I was in the future.

**Comment by ai** [comment]
@Pomax we wrote a message together. I close it because of https://github.com/ai/browserslist/issues/109#issuecomment-274281067

**Comment by Pomax** [comment]
I understand that, but the best way to answer a question that isn't covered by a README is to make sure it ends up in the README so that it's not an answer "for this one person asking" but an answer for everyone who might have this question. They're not going to find the answer in a closed issue, google doesn't really care about those =)

**Comment by ai** [comment]
@Pomax sure. I agree that we should add something. What do you want to add?

**Comment by Pomax** [comment]
Hmm, probably adding the "scripts" line to the code to show it as a self-contained example, since there is already example code for using it in JS context (which also covers gulp/grunt/webpack/etc)

**Comment by ai** [comment]
@Pomax or maybe we could replace

```md
In `package.json`:
```

to

```md
All tools find browserslist config automatically, Just add to `package.json`:
```

What do you prefer?

**Comment by Pomax** [comment]
As long as we list the actual tools, the second might be better! Would this work?

```
All tools that rely on `autoprefixer` will find the browserslist config automatically,
as long as it's configuration can be found either in the `package.json` or its own
configuration file as mentioned above
```

**Comment by ai** [comment]
@Pomax why `rely on autoprefixer`? Stylelint, Babel and ESLint uses browserslist, but don’t rely on Autoprefixer.

Also we need more shorter text. People ignore long texts.

> All tools that rely on browserslist will find its config automatically. Just add to `package.json`:

And we could remove `autoprefixer` from `package.json` example to be more clear about independence with Autoprefixer.

**Comment by ben-eb** [comment]
@ai Perhaps it might be nice to have a list of modules that rely on Browserslist in the readme file? That way we can highlight other tools than Autoprefixer and create a nice ecosystem around Browserslist.

**Comment by ai** [comment]
Yeap. But I wait for correct implementation from Babel. @hzoo any ETA?

**Comment by Pomax** [comment]
In that case yes: if there's a known list, showing that list will have high value. Based on the README.md I assumed this was purely for autoprefixer =)

**Comment by ben-eb** [comment]
@Pomax npm give you this data already. 😄

https://www.npmjs.com/browse/depended/browserslist

**Comment by Pomax** [comment]
Remember that anything that's only visible on `npm`, will be *invisible* to everyone who finds this through google, or gets linked directly =)

**Comment by ai** [comment]
So, it is OK?

```
All tools that rely on browserslist will find its config automatically. Just add to package.json:
```

**Comment by ben-eb** [comment]
> All tools that rely on browserslist will find its config automatically, when you add the following to `package.json`:

**Comment by ai** [comment]
Done 41d610b
