### ISSUE TITLE
Suggestion: allow loading browser stats form npm module

### ISSUE THREAD

**Issue by jrencz** [ai/browserslist#113]
I'd like to suggest that there should be a way to express browser usage stats from a module.

It may be useful in case one wants to have the browser statistics shared across many projects.
In such case storing the stats JSON in project will not be enough.

How about allowing `stats` option to be a name of node module? `main` of that module would have to resolve to valid stats object (it may be json or JS)

**Comment by ai** [comment]
Just use `stats: "node_module/some-name/stats.json"`
