### ISSUE TITLE
"last n versions" includes unstable ones

### ISSUE THREAD

**Issue by mgol** [ai/browserslist#115]
One could expect that e.g. specifying "last 3 Chrome versions" will be reasonably safe as that's what's promoted in README. However, that's not the case:
```
$ browserslist "last 3 Chrome versions"
chrome 59
chrome 58
chrome 57
```

This includes ONLY unstable versions of Chrome. That's not good.

**Comment by ai** [comment]
Unstable versions are unreleased yet. So it is not a version yet and just a plan.

**Comment by mgol** [comment]
That's exactly the problem! Unstable versions shouldn't be included and they are.

Why did you close the issue?

**Comment by ai** [comment]
Ouh

**Comment by ai** [comment]
@ben-eb is it related with recent changes?

**Comment by ben-eb** [comment]
I'm not sure, is it anything to do with the `null` versions that we filtered out? All tests were passing at that time.

**Comment by ai** [comment]
@ben-eb yeap, it should be related to `null`

**Comment by ai** [comment]
Here is a bug. You had two different arrays and now 2 same:

```diff
+            versions: normalize(caniuse[name].versions),
+            released: normalize(caniuse[name].versions.slice(0, -3))
-            versions: browser.versions,
-            released: browser.versions
```

**Comment by ai** [comment]
@ben-eb  Can I Use uses 2 first versions for unreleased versions. If there is no 2 versions yet, it use `null` there.

So we can’t just remove `null` version, we need to split version to released and unreleased.

**Comment by ben-eb** [comment]
OK, but I'm busy today. Might be able to pull request later in the week?

**Comment by ai** [comment]
I will revert that changes today. We need to fix it in `caniuse-lite` API.

**Comment by ai** [comment]
@ben-eb fix — first 3 versions is “unreleased”

**Comment by ai** [comment]
Released in 1.7.1

**Comment by mgol** [comment]
Thanks! Now we only need a new Autoprefixer release.

**Comment by ai** [comment]
@mgol Autoprefixer don’t need a release (just update dependency). Autoprefixer Rails release will be in few minutes (I am waiting for Travis CI)

**Comment by mgol** [comment]
@ai Latest Autoprefixer depends on `browserslist@~1.6.0` so it won't pick up `browserslist` `1.7.1`. So I think it does need a new release.

**Comment by ai** [comment]
Fuck, I forget to update browserslist :D.

**Comment by ai** [comment]
Done. 6.7.1 was released.
