### ISSUE TITLE
No compatible version found: electron-to-chromium@^1.2.2

### ISSUE THREAD

**Issue by krewedehughes** [ai/browserslist#119]
If I try to do `npm i browserslist --save` I get this error:
`npm ERR! notarget No compatible version found: electron-to-chromium@^1.2.2
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.1, 1.0.0`

We weren't experiencing this problem last week; it started this week.  We found out about it because css-loader has a dependency on browserslist.

**Comment by ai** [comment]
I will debug it few hours later. Please downgrade browserslist to previous release.

**Comment by krewedehughes** [comment]
My company's mirror needs to upgrade electron-to-chromium; sorry for opening the issue when it turns out it's on my end.
