### ISSUE TITLE
Typo - stray bracket character

### ISSUE THREAD

**Issue by michaelschwobe** [ai/browserslist#121]
```javascript
if ( typeof opts === 'undefined' ) opts = s };
```

**Comment by ai** [comment]
@michaelschwobe next time always write where you find mistake ;).

I don’t understand where it is.

**Comment by michaelschwobe** [comment]
Sorry... was distracted. within index.js line 146 it looks like:

```javascript
    if ( typeof opts === 'undefined' ) opts = { };
```
but when using npm install or yarn, index.js line 48 looks like:

```javascript
    if ( typeof opts === 'undefined' ) opts = s };
```

**Comment by ai** [comment]
I tried fresh install and everything is fine.

Also with 250K everyday downloads Twitter will be full of angry tweets :D.

I think you have problem with npm cache. Try `yarn cache clean` and remove `~/.npm`.
