### ISSUE TITLE
Add CLI tests

### ISSUE THREAD

**Issue by ai** [ai/browserslist#126]

**Comment by vvscode** [comment]
https://github.com/ai/browserslist/pull/132

Will be the approach ok? If yes, I'll add others

**Comment by zhulduz** [comment]
I was late)

I have also first attempt with tests for cli.js https://github.com/zhulduz/browserslist/tree/cli-tests, but it hasn't finished yet.

**Comment by ai** [comment]
@zhulduz this PR is not finished and maybe need to be rewritten, so you are not late :)

**Comment by ai** [comment]
@zhulduz using `spawn` is nice. Could you merge all test files to single file? What do you need write more in your branch?

**Comment by zhulduz** [comment]
@ai 
Ok, I'll merge)
I want to add tests for params `coverage, config, env, stats`

**Comment by ai** [comment]
@zhulduz good, if you will finish it today, you will solve this task :)

**Comment by vvscode** [comment]
@zhulduz sorry )) I don't know if someone start to work on it. My PR is closed
