### ISSUE TITLE
Multiple browser versions by market share

### ISSUE THREAD

**Issue by bencevans** [ai/browserslist#130]
Hi,

How would I go about writing a query that outputted every version of each browser with more than 3% market share? It appears caniuse has the data from looking at http://caniuse.com/usage-table

It would be useful to have something added to the docs.

So far I've got the most recent version of each browser that has more than 3% usage but not all the versions of each browser with [`>3%, iOS >=9, Android >=4.4`](http://browserl.ist/?q=%3E3%25%2C+iOS+%3E%3D9%2C+Android+%3E%3D4.4)

Cheers,

Ben

**Comment by ai** [comment]
Hm. For what use case you need it?

**Comment by bencevans** [comment]
To generate a list of all browser/versions needed to be tested against.

**Comment by ai** [comment]
@bencevans so if Chrome have more than 3% Browserslist must output Chrome from 0 to latest?

**Comment by bencevans** [comment]
No more like if Chrome 51 & Chrome 52 has above 3% usage then both are listed. It appeared only the most recent version of a browser that fitted the 3% rule would show and no other versions.

**Comment by ai** [comment]
It is current `>3%` behaviour — returns version is market more than `%3`.
