### ISSUE TITLE
Why Chrome for Android not showing here?

### ISSUE THREAD

**Issue by jitendravyas** [ai/browserslist#136]
http://browserl.ist/?q=last+2+version%2C+not+IE+11%2C+not+Opera+43%2C+not+ie_mob+11%2C+not+ie_mob+10%2C+not+Opera+42

**Comment by ai** [comment]
Because `last n browsers` shows only “major” browsers. We already planed to change it in next major release https://github.com/ai/browserslist/issues/98

**Comment by jitendravyas** [comment]
only “major” browsers ? but Chrome on mobile is most used browser I think

**Comment by ai** [comment]
@jitendravyas we will fix it in next major release. It will in next few weeks. Anyway I could not change it without major release.
