### ISSUE TITLE
How to exclude all versions of a browser?

### ISSUE THREAD

**Issue by jitendravyas** [ai/browserslist#137]
I want to exclude Opera and IE but currently, I need to mention each version http://browserl.ist/?q=last+2+version%2C+not+IE+11%2C+not+Opera+43%2C+not+ie_mob+11%2C+not+ie_mob+10%2C+not+Opera+42

Is there something like `not opera`

**Comment by ai** [comment]
`not Opera > 0`.

But I do not recommend it. Opera still popular browser with many users. Web should be accessible for all browsers.

Also modern Opera is like Chrome, you should not afraid it.

**Comment by jitendravyas** [comment]
`not IE Mobile > 0` not working

http://browserl.ist/?q=last+3+versions%2C+not+IE+%3E+0%2C+not+Opera+%3E+0%2C+not+IE+Mobile+%3E+0

**Comment by FateRiddle** [comment]
@ai  How do you exclude op_mini? Tried 'not op_mini > 0', and 'op_mini all' is still there.

**Comment by ai** [comment]
@FateRiddle `not op_mini all`

Don't forget that Opera Mini is very popular in Africa. So consider it twice and remove it only when it is totally technically impossible to support it.

**Comment by renielDev** [comment]
how to exclude IE? i tried not `IE > 0` but it still showing

**Comment by ai** [comment]
Don't forget about `IEMob > 0`. Use `npx browserslist` for debugging.

**Comment by wickkidd** [comment]
I know I'm beyond late to the party, but it would be nice if not specifying a version was equivalent to specifying all versions. E.g. `not ie` == `not ie >= 0`

**Comment by ai** [comment]
> it would be nice if not specifying a version was equivalent to specifying all versions.

Removing support for all versions of some browser is the bad practice for our perspective of view. I grow up in Russia, where the most popular browser (Opera) was no familiar to Western developers (so they mostly avoid to support it).

We do not have simple query for this by design.

**Comment by jonybuzz** [comment]
I´m developing a cordova app that is targeted only for Android, so "not ie" would be nice to make the code lighter

**Comment by ai** [comment]
@jonybuzz you can create sharable config like `browserslist-config-cordova`.

Unfortunately, I can’t ad feature for a rare use case, which will force bad practice for a lot of users. I think it is OK to have hacks for rare cases.

**Comment by omarryhan** [comment]
This should be included in the README imo.

**Comment by warlockuk** [comment]
I too would like to exlude all IE support and polyfill code - Let IE die.  I do not want my products to support it.  The more it can die the quicker it will be less of an issue.

Also it doesn't support key things I use anyway

**Comment by ai** [comment]
@warlockuk `IE > 0`

**Comment by fabiank0** [comment]
Hi, as a test I've put in development
`    "development": [
      "last 1 firefox version",
      "not Safari > 0",
      "not Chrome > 0",
      "not ios_saf > 0"
    ]`
But this is not working for me. I can use Safari/Chrome just fine on localhost. Am I missing something?

**Comment by jaydenseric** [comment]
@fabiank0

> I can use Safari/Chrome just fine on localhost. Am I missing something?

Probably because watever code you're testing works fine in those browsers.

**Comment by Herz3h** [comment]
`not op_mini > 0` didn't work in my case, had to use `not op_mini all`
