### ISSUE TITLE
How to create browserlist config file?

### ISSUE THREAD

**Issue by jitendravyas** [ai/browserslist#138]
is it .browserlistrc like .stylelintrc?

**Comment by ai** [comment]
Nope. It is `browserslist` name. Or `browserslist` key in `package.json`.

**Comment by jitendravyas** [comment]
Do you mean like this with no `.` in starting? 

![image](https://cloud.githubusercontent.com/assets/77309/24950973/73d4d7ba-1f90-11e7-9860-b2402d099881.png)

**Comment by ai** [comment]
Yeap. No dot.

In next major we are thinking to support `.browserslistrc` too. But `browserslist` key in `package.json` is better anyway.

**Comment by jitendravyas** [comment]
What will be the benefit of `.browserslistrc` over `browserslist`? just a name change?

**Comment by ai** [comment]
Yeap, just file name.

Content looks fine.

**Comment by rpellerin** [comment]
What is the preferred file these days? `.browserslistrc` or `browserslist`?

**Comment by ai** [comment]
@rpellerin `.browserslistrc` because it copies the style of other configs and fix rare bug with npm

**Comment by rpellerin** [comment]
@ai thank you!
