### ISSUE TITLE
not [...] query not working?

### ISSUE THREAD

**Issue by seaneking** [ai/browserslist#139]
No matter what I do I can't get the `not ...` query to work in my browserslist configs.

If I'm understanding correctly, the following query should result in targeting IE11 + last 2 versions of all other browsers:

```
last 2 versions, not ie < 11
```

But when I specify that in `package.json` or a `browserslist` config file autoprefixer is still generating IE10 styles.

**Comment by ai** [comment]
Everything work in online some:
http://browserl.ist/?q=last+2+versions%2C+not+ie+<+11

Maybe:

1. You got mobile IE 10
2. You have environment problems

**Comment by seaneking** [comment]
Yep was accidentally targeting IE10 mobile, my bad. Apologies for the unnecessary issue.
