### ISSUE TITLE
Supporting `>=` operator for versions

### ISSUE THREAD

**Issue by evilebottnawi** [ai/browserslist#141]
Why? Example on `autoprefixer`, I want to add prefixes when at least the browser uses one of a thousand (`>= 0.1%`), but now i can do this using `>= 0.09%`. It is implicit and not very convenient. I can do PR if your accept.

**Comment by Semigradsky** [comment]
browserslist supported `>=`

**Comment by evilebottnawi** [comment]
@Semigradsky 
```
>= 0.1%
```

```shell
browserslist: Unknown browser query `>= 0.1%`
```

**Comment by ai** [comment]
Done 66eaa16

**Comment by ai** [comment]
Released in 2.1 version
