### ISSUE TITLE
Possible string interpretation bug

### ISSUE THREAD

**Issue by d4rkne55** [ai/browserslist#142]
I am using the Autoprefixer plugin for Sublime 3 (latest) and the following browserslist string:
`> 1%, last 2 versions, not IE < 9, not BlackBerry < 10`

Autoprefixer then adds webkit vendor prefixes for linear-gradients, among others. According to caniuse this shouldn't happen though: https://caniuse.com/#feat=css-gradients

The only browser needing the prefix with the default browserslist config would be Blackberry 7 - this matches with my string without the not's.

Could there be a misinterpretation of the `not` clauses then or what else could be the problem?

Thanks in advance!

**Comment by ai** [comment]
You can use Browserslist CLI or you website (see in GitHub project header) to get what browsers will be used.

Also by calling `autoprefixer({ browsers }).info()` you can get a reason for every prefix.

If you will find mistake in this data, feel free to open new issue.
