### ISSUE TITLE
Can not use 'QQAndroid' in browserslist

### ISSUE THREAD

**Issue by Jack-Sparrow** [ai/browserslist#144]
When use `"last 2 QQAndroid versions"` in `browserslist` of `package.json`, got error: `Module build failed: BrowserslistError: Unknown browser QQAndroid`, but it's ok when use `and_qq` instead of `QQAndroid`.

```
"browserslist": [
    ...
    "last 2 QQAndroid versions"
  ]
```

```
Module build failed: BrowserslistError: Unknown browser QQAndroid
```

I use autoprofixer in postcss-loader in webpack

**Comment by ai** [comment]
QQAndroid works in Browserslist 2. Only Autoprefixer 7 will use Browserslist 2. I want to release Autoprefixer 7 today or tomorrow.
