### ISSUE TITLE
Idea : Year queries

### ISSUE THREAD

**Issue by Swizz** [ai/browserslist#145]
Hi there,

ATM Browserslist allow some queries : Version number, Last version count, Use stats.

Recently, we have a case when a client ask us to support browsers since 2013.
And we did a laborious work to find version from this date.  So, it could be great to did this job like browserslist do, for the benefits of all the comunity.

I could try to work on a PR, if I have time.

Guys, what do you think ?

Cheers,

**Comment by Swizz** [comment]
Unfortunately caniuse-db does not provide release date despite the website does it

**Comment by ai** [comment]
Cool idea. But we need years data from Can I Use.

You can create a issue there.

**Comment by tconnard** [comment]
This seems to contain the necessary dates in the form of *nix timestamps.
https://github.com/Fyrd/caniuse/blob/master/fulldata-json/data-2.0.json

**Comment by ben-eb** [comment]
@ai No, we don't expose the `version_list` object. Of course, pull requests are welcome. 😄

**Comment by blicksky** [comment]
This issue can be closed now, no?

**Comment by ai** [comment]
Released in 2.7
