### ISSUE TITLE
What change should I make here after browserlist 2 to get same result?

### ISSUE THREAD

**Issue by jitendravyas** [ai/browserslist#146]
my `browserslist` file

```
last 3 versions
not IE > 0
not ExplorerMobile > 0
not iOS > 0
```

Context https://github.com/postcss/autoprefixer/issues/842#issuecomment-302079580

**Comment by lydell** [comment]
There's no reason to try to get the same result as before.

**Comment by jitendravyas** [comment]
ok.

**Comment by jitendravyas** [comment]
Can anyone please help me on What will be the Version 2 format of this?

```
last 3 versions
not IE > 0
not ExplorerMobile > 0
not iOS > 0
```

**Comment by ai** [comment]
Format is the same.

**Comment by ai** [comment]
Why you need only some browsers and not all?

**Comment by jitendravyas** [comment]
Because we want to spend time making our B2C app compatible on browser we need only which are mainly desktop (99% in GA). 

This new change in browserlist has broken our build because I was using this plugin https://github.com/ismay/stylelint-no-unsupported-browser-features

For now, I have temporary disable this plugin unless I get the same list of browsers as previous.

**Comment by ai** [comment]
Supporting only desktop browsers is very bad practice. Mobile market is much bigger and most of your users have mobile browser.

What exactly problems do you have with `stylelint-no-unsupported-browser-features`?

**Comment by jitendravyas** [comment]
I know supporting desktop browsers only could be bad practice but our app has 99% users from desktop browsers. There are many web apps which don't have RWD even from google.

 After browserlist 2 and with same browserlist config `stylelint-no-unsupported-browser-features` is showing errors for many browser, even Opera mini.

**Comment by ai** [comment]
If you didn’t want to support Opera Mini, just exclude it from browsers: `last 2 version, not operamini > 0`

**Comment by jitendravyas** [comment]
I have this in browser list now but Opera mini warnings are still coming

```
last 3 versions
not IE > 0
not ExplorerMobile > 0
not iOS > 0
not OperaMini > 0
```

**Comment by ai** [comment]
@jitendravyas `last 3 versions, not IE > 0, not ExplorerMobile > 0, not iOS > 0, not OperaMini all`

**Comment by jitendravyas** [comment]
Don't know why these are not working

```
not BlackBerry all
not OperaMobile all
not Android all
```

**Comment by jitendravyas** [comment]
Ok, I found it. It's bit confusing for some browser it's not OperaMini `all` and for some it's not OperaMobile `> 0`

last 3 versions, not IE > 0, not ExplorerMobile > 0, not Samsung > 0, not OperaMobile > 0, not iOS > 0, not BlackBerry >0, not Android > 0, not OperaMini all, not QQAndroid > 0, not UCAndroid > 0

By the way, I'm trying above code and  `not QQAndroid > 0, not UCAndroid > 0` still not working and didn't see an option to remove `Baidu Browser`

link http://browserl.ist/?q=last+3+versions%2C+not+IE+%3E+0%2C+not+ExplorerMobile+%3E+0%2C+not+Samsung+%3E+0%2C+not+OperaMobile+%3E+0%2C+not+iOS+%3E+0%2C+not+BlackBerry+%3E0%2C+not+Android+%3E+0%2C+not+OperaMini+all%2C+not+QQAndroid+%3E+0%2C+not+UCAndroid+%3E+0

**Comment by ai** [comment]
You can use `not last 1 QQAndroid version`.

Unfortunatelly, `caniuse-db` is very inconsistency in browser version :(. `OperaMini all` is not a query, `all` is version number according `caniuse-db` :(

**Comment by jitendravyas** [comment]
Thanks. What to do for Baidu Browser?

**Comment by ai** [comment]
If you have exactly list of browsers, just mention them: `last 3 Chrome versions, last 3 Firefox versions, …`

**Comment by jitendravyas** [comment]
I think this doesn't work completly or this plugin is not working perfectly https://github.com/ismay/stylelint-no-unsupported-browser-features

I have only these in my browserslist file

```
last 3 Chrome versions
last 3 Firefox versions
last 3 Edge versions
last 3 Opera versions
last 3 ChromeAndroid versions
```

but still get warnings for other browsers

![2017-06-17 11-22-17](https://user-images.githubusercontent.com/77309/27250498-4bd3ff1e-534f-11e7-8f0f-9102bb2ede62.jpg)

**Comment by ai** [comment]
This query doesn’t include Baidu http://browserl.ist/?q=last+3+Chrome+versions%2C+last+3+Firefox+versions%2C+last+3+Edge+versions%2C+last+3+Opera+versions%2C+last+3+ChromeAndroid+versions

Maybe you have problems with cache or Stylelint load wrong config

**Comment by jitendravyas** [comment]
I have no other config setup anywhere else only `browserslist` file in the project root. 

What do you mean by `cache` in this case? Maybe this is a problem with the plugin https://github.com/ismay/stylelint-no-unsupported-browser-features of @ismay

**Comment by ismay** [comment]
@jitendravyas When using stylelint-no-unsupported-browser-features it's recommended to set the plugin to output warnings, not errors. See the readme:

> This is a good rule to use with "warning"-level severity, because its primary purpose is to warn you that you are using features not all browsers fully support and therefore ought to provide fallbacks. But the warning will continue even if you have a fallback in place (it doesn't know); so you probably do not want this rule to break your build. Instead, consider it a friendly reminder to double-check certain spots for fallbacks.

https://github.com/ismay/stylelint-no-unsupported-browser-features#recommendations

The config that you'll need for that setup is in the readme as well.

**Comment by jitendravyas** [comment]
@ismay Thanks for the explanation though I already know about it. I kept it as a Error temporary so I can identify it quickly from the long list of errors. The problem which I assume (could be wrong) that it's not detecting `browserlist` file properly. See this issue https://github.com/ai/browserslist/issues/146#issuecomment-309195645

**Comment by jitendravyas** [comment]
Because of the issue, I might have to remove `stylelint-no-unsupported-browser-features` plugin from my project. I keep getting long warnings for Baidu browser.

**Comment by jitendravyas** [comment]
@ai You were right here https://github.com/ai/browserslist/issues/146#issuecomment-309224908

**Comment by vincent-louis** [comment]
Hi @jitendravyas have you try"not OperaMini all" ?
