### ISSUE TITLE
Some browser keywords not working

### ISSUE THREAD

**Issue by jitendravyas** [ai/browserslist#147]
Not working

QQAndroid or and_qq for QQ Browser for Android.
UCAndroid or and_uc for UC Browser for Android.
OperaMini or op_mini for Opera Mini.

And what is keyword for Baidu?

`last 3 versions, not IE > 0, not ExplorerMobile > 0, not iOS > 0, not BlackBerry > 0, not Android > 0, not OperaMobile > 0, not and_qq > 0, not OperaMini > 0, not UCAndroid > 0`

http://browserl.ist/?q=last+3+versions%2C+not+IE+%3E+0%2C+not+ExplorerMobile+%3E+0%2C+not+iOS+%3E+0%2C+not+BlackBerry+%3E+0%2C+not+Android+%3E+0%2C+not+OperaMobile+%3E+0%2C+not+and_qq+%3E+0%2C+not+OperaMini+%3E+0%2C+not+UCAndroid+%3E+0

**Comment by ai** [comment]
Use `>=`, instead of `>`.

It is is very bad to remove this browsers. There is a lot of users for them.

**Comment by jitendravyas** [comment]
I know but I'm working on enterprise web app for specific use cases. Our GA shows 1% traffic from mobile and we are not focusing to build it for mobile.

**Comment by jitendravyas** [comment]
`>=` for all or for those which are not working?

**Comment by ai** [comment]
So why you need to remove all this prefixes? Gzip compress it perfectly. You didn’t loose anything with this prefixes.

**Comment by jitendravyas** [comment]
I need to remove because I use Doiuse too and the more browsers we add, the more warnings i could get for css properties/values w

**Comment by konstantin24121** [comment]
Why this close? I have same error with QQAndroid  and UC, and where is Baidu?

**Comment by ai** [comment]
@konstantin24121 because it is how Can I Use return a data. Open issue there.
