### ISSUE TITLE
How to target last 2 versions of FF ESR?

### ISSUE THREAD

**Issue by ZebraFlesh** [ai/browserslist#148]
How can I target the last 2 versions of FF ESR?  If I use `last 2 versions`, I only get FF 52 and 53; I would expect to get FF 45, 52, 53:

* 53 is latest FF
* 52 is previous version of FF, plus latest FF ESR
* 45 is previous FF ESR

Using the demo at http://browserl.ist it does not seem possible to write a query that pulls in "the last two versions of Firefox ESR".

This is important because there's always a qualification period during which the previous ESR version and the next ESR version overlap, so they're both active and supported for a time (such as right now). Also, institutions/enterprises are notoriously slow to upgrade, so it would be nice to be able to target N versions back, based on the target audience.

**Comment by ai** [comment]
I have better solution. What do you think if Browserslist will return `firefox 52, firefox 45` on `firefox esr`?

So `firefox esr` will  return actual ESRs.

I think there is no sense to return old non-supported ESRs.

**Comment by ZebraFlesh** [comment]
That's certainly better than what exists today.

However, I'd prefer if Firefox ESR was actually queryable by version.  It seems weird that it's the only browser which cannot be version queried: it is a separate browser with it's own feature set and release schedule. A reasonable approximation would be to match the features for any given FF ESR release onto the corresponding FF release. So FF ESR 45.9.0 maps to FF 45, but could then be queried by `last 2 Firefox ESR versions`, or 3, or however many I wanted -- like all the browsers.

**Comment by ai** [comment]
ESR is not a browser, it is a version alias.

What is your use case to select 3 ESR versions? Or to select 2, when only one is supported?

**Comment by ZebraFlesh** [comment]
Why do you allow people to select `ie 6-8`? Because they're still used. Just because something is unsupported doesn't mean it's not used.

**Comment by ai** [comment]
Why selecting it y version `Firefox 42, Firefox 38` doesn't fit your needs.

`last 3 ESR versions` also doesn't have semantics reasons. ESR is supporting level. When Mozilla stop to support a version, it could not called ESR anymore.

**Comment by ZebraFlesh** [comment]
> Why selecting it y version Firefox 42, Firefox 38 doesn't fit your needs.

Because I want to use a semantic query string such as "last N versions". Using hard coded values means I need to update my list of browsers whenever there's a new ESR release.

> last 3 ESR versions also doesn't have semantics reasons. ESR is supporting level. When Mozilla stop to support a version, it could not called ESR anymore.

Maybe this is our point of confusion. ESR is not just a support level: it is a distinct software baseline. Here's the repo for ESR 45: https://hg.mozilla.org/releases/mozilla-esr45/ It is definitely a separate piece of software. When the Mozilla Foundation stops supporting a particular ESR release, the tag does not disappear from the repo. (Go up a level and you can go all the way back to the ESR 10 baseline.) It's still an ESR, just an unsupported one -- the same way that Microsoft no longer supports IE 8.

**Comment by ai** [comment]
What exactly use case do you have for selecting 3 ESR versions?

IE 6-9 example doesn't fit it, because you support 6 because you have users with it, not because it is `last 6 IE versions`.

`last n versions` used mostly for `last 2 versions`. Modern browsers have autoupdate. When Chrome n+1 will be released some users will be on Chrome n because of autoupdate lag. But I don't see any reasons for semantic request of `last 4 versions`.

Let's me explain my concerns with dealing with Firefox ESR as separated browser:

1. It will require major release.
2. Can I Use doesn't deal with Firefox ESR browser. So it will require increase Browserslist code complexity and reducing maintability.
3. Most of developers don't think about Firefox ESR as separated browser. So they will be surprised too see unsupported previous Firefox ESR in `last 2 versions` query (it loads all browsers, so with you suggestion it will load last 2 Firefox ESR versions too).

As you can see, I need really good reason for making Firefox ESR as separated browser.

**Comment by ZebraFlesh** [comment]
It's simple: organizations and enterprises are slow to upgrade and do not follow the Mozilla schedule. There's likely a number of intranets that are still running ESR 38 because they haven't upgraded their infrastructure. Those computers are locked down and cannot be autoupdated by users. Organizations running ESR 38 at this point are just a little slow and are [just under a year out of date](https://wiki.mozilla.org/images/9/9d/Esr-release-overview.png). That doesn't seem like a good reason to punish those users.

I don't think this requires a new version in the code. You're already aliasing ESR to a particular Firefox version. Why not just alias it to a list and make it synthetic browser version in order to support the queries with browserlist? If you were tracking bugs, this wouldn't be right; however, you're tracking browser capabilities and ESR freezes those upon first release, so this approach sounds correct.

> Most of developers don't think about Firefox ESR as separated browser. So they will be surprised too see unsupported previous Firefox ESR in last 2 versions query (it loads all browsers, so with you suggestion it will load last 2 Firefox ESR versions too).

And I was surprised to see browsers that are primarily used in China (it's not my target market). People will adjust the same way they did with how the 2.0 release changed the `last 2 versions` results.

**Comment by ai** [comment]
> Those computers are locked down and cannot be autoupdated by users. Organizations running ESR 38 at this point are just a little slow and are just under a year out of date. That doesn't seem like a good reason to punish those users.

If it is not autoupdated machines, why you are think that `last 3 ESR versions` is good for this companies? You think they update Firefox 38 when Mozilla will release next ESR?

**Comment by ZebraFlesh** [comment]
Having worked with one of those large organizations, I can tell you they have an upgrade schedule. If it's "upgrade annually", that often translates to 12-14 months. So `last 3 ESR versions` would cover them.

**Comment by ai** [comment]
“Annually update” doesn’t semantically equal to “last 3 versions”.

Also you didn’t show me how I can fix other problems with “ESR as separated browser”. For my perspective it will be worse for everyone else and better only for you.

Writing `firefox 38, firefox 42` will solve your problem and keep other 4-5 M developers happy.

**Comment by ai** [comment]
Done https://github.com/ai/browserslist/commit/afc8bd3bc057acb71fe2aa9ecef7768655c83b7d

**Comment by ai** [comment]
> Do you have last two ESR versions hardcoded and update them when new ones do came out ?

Yes, they are hardcoded, and I update and release new Browserslist every time. Please keep it up to date (and update `caniuse-db` too).
