### ISSUE TITLE
Idea: targeting all versions of a browser / all browsers

### ISSUE THREAD

**Issue by jonathantneal** [ai/browserslist#151]
Sometimes I use a browser list for individual parts of my app, like I do in [PostCSS Normalize](https://www.npmjs.com/package/postcss-normalize).

For instance, I might have a fix for _all versions_ of IE. Right now, to mark this up I write `ie > 0`, but could it instead be `ie`?

In another instance, I might have a fix for _all browsers_. Right now, to mark this up I write `> 0%`, but could it instead be `all`?

**Comment by 11bit** [comment]
Hi @jonathantneal,

Thx for proposal and PR. @ai is currently on vacation on Cuba (and he doesn’t have Internet there). He will return at Jun 9 and look as maintainer. Is it OK?

**Comment by jonathantneal** [comment]
@11bit, yes, of course. Would you be able to give it a review for him in the meantime?

**Comment by ai** [comment]
I agree that many developers want it, but I think it is bad practice to select all browsers. Anyway you cover will not work in Chrome 3.

This is why I closed all previous suggestions for `all` to forced use developers to create good browsers policy.

And you can still select all by `chrome > 0`.

**Comment by ai** [comment]
If somebody will have good and popular use case for this query, I will open issue/PR again :).

**Comment by jonathantneal** [comment]
I plan for postcss-normalize / normalize.css to be built from individual source files that leverage browserslist. I’m sad that they will look so hard to read. I went through the repo today to see something like his had ever made it in.

| What I Wish Worked | What Actually Works |
| --- | --- |
`any`, `all` | `>= 0%`
`any ie`, `all ie` | `ie > 0`, `ie <= 11`

And sometimes on projects I want this:

```
last 2 versions
not dead
not any ie
```

**Comment by ai** [comment]
I know that there are legit use cases for these queries. But I afraid that song this query to Browserslist will promote bad practice.

`> 0` requires more experience in software development. So developer more likely will know what they do.

I am thinking about it like a barrier only for advanced developers.

What do you think about it?
