### ISSUE TITLE
Support Set/WeakSet. And maybe generators 😲.

### ISSUE THREAD

**Issue by yavorsky** [ai/browserslist#153]
Actually, I've started some work on it, but want to see some kind of approval.

The main idea is to allow using Set/WeakSet as a browsers query. Browserslist supports both Sting and Array, so it at least intent to be flexible for different formats provided by the user.

Example:
```js
var myQuery = new Set();

myQuery.add('last 2 chrome versions');
myQuery.add('safari 10');
myQuery.add('ie 9');

const browsers = browserslist(myQuery);
```

Also, to parse it we could use for..of. So it would allow accepting any iterable things. For example, generators:

```js
function* myQuery(browserslistOpts) {
  yield 'safari 10'
  if (time === '4:19') {
    yield '>1%'
  } else if (time === '4:20') {
    yield 'last 1 chrome version';
  }
  if (browserslistOpts.env === 'production') yield* prodQuery();
  if (timezone === 'usa') yield '> 5% in US';
}
```

What do you think?

**Comment by ai** [comment]
😄 I don't know any disadvantages of this. But I am not sure, that somebody really needs it and it is not trend-based-development.

But let's try to make PR to understand will we have a problem with it.
