### ISSUE TITLE
2.2.1 breaks stylelint

### ISSUE THREAD

**Issue by hudochenkov** [ai/browserslist#158]
Sorry, for creating an issue in this manner. I have no time to investigate right now. I'm not sure if it's browserslist's issue, or stylelint's. But we just received two issues about browserlist error, and new browserlist version just released.

https://github.com/stylelint/stylelint/issues/2775
https://github.com/stylelint/stylelint/issues/2774

**Comment by pvdyck** [comment]
linked issue : https://github.com/ionic-team/ionic/issues/12441

**Comment by XhmikosR** [comment]
I didn't know who to blame and I couldn't pinpoint the cause so as first since stylelint was being loaded the error came from there. Then after removing stylelint I was getting the same error in autoprefixer, so I reported it [there](https://github.com/postcss/autoprefixer/issues/865) instead.

I guess I should have reported the issue here, sorry for that.

From my findings using browserslist 2.1.5 works but when 2.2.1 is used I'm getting this error.

**Comment by hinaloe** [comment]
browserslist@2.2.0 is work well, but 2.2.1 is having this bug :(

**Comment by XhmikosR** [comment]
That is good news! We have at least pipointed where the issue started to happen, now just someone needs to submit a fix and release a new patch build asap.

**Comment by hinaloe** [comment]
https://github.com/ai/browserslist/commit/9d3e5de995a5f560452c6f9457f41e25b5634924?w=1#diff-168726dbe96b3ce427e7fedce31bb0bcR78

**Comment by XhmikosR** [comment]
Yeah that seems to be the exact cause. Submitted #159.

**Comment by pieterbeulque** [comment]
@hinaloe & @XhmikosR — thanks for your work. Didn't see the #159 PR so added one myself with an extra test, hoping to speed up a patch release.

**Comment by phlax** [comment]
> Sorry, for creating an issue in this manner. I have no time to investigate right now.

wow you wasted a lot of other peoples time

**Comment by ai** [comment]
> Sorry, for creating an issue in this manner

:D You did everything right. Browserslist used by Autoprefixer with the big user base. False alarm, in this case, is better rather than thousands of wasted hours by Autoprefixer users.

Sad that issue was founded only when I went to sleep (other good reason to report it faster).

**Comment by phlax** [comment]
apologies to OP, im sure it wasnt his fault 8/
