### ISSUE TITLE
Symlinks not honored when finding the config file

### ISSUE THREAD

**Issue by moll** [ai/browserslist#16]
Hey,

Because Browserslist uses `lstat` and not `stat`, symlinking the `browserslist` file doesn't work. It should. Symlinks are useful. ;-)

Cheers

**Comment by ai** [comment]
Yeap. Can you send me a PR? I am very busy on this week :(.

**Comment by ai** [comment]
Done 99d3ffc

**Comment by ai** [comment]
And second fix 8b05c9c

**Comment by moll** [comment]
Thanks! Can confirm this one works too.
