### ISSUE TITLE
Caniuse.com shows Microsoft Edge 16 for CSS grid but browserlist show till 15 only in last 3 edge version.

### ISSUE THREAD

**Issue by jitendravyas** [ai/browserslist#162]
http://caniuse.com/#search=grid

![monosnap 2017-07-31 14-11-20](https://user-images.githubusercontent.com/77309/28769744-5436fa26-75fa-11e7-90c0-28ec7e4c2792.jpg)

http://browserl.ist/?q=last+3+Chrome+versions%2C+last+3+Firefox+versions%2C+last+3+Safari+versions%2C+last+3+Edge+versions%2C+last+3+Opera+versions%2C+last+3+ChromeAndroid+versions%2C+last+3+FirefoxAndroid+versions%2C+last+3+iOS+versions%2C+last+3+Samsung+versions

**Comment by ai** [comment]
What `caniuse-lite` version do you use?

**Comment by jitendravyas** [comment]
How to know that?

**Comment by ai** [comment]
Open `node_modules/caniuse-lite/package.json`. You should update it to the latest version (`1.0.30000708`) to have latest Can I Use data.

**Comment by jitendravyas** [comment]
caniuse-lite@1.0.30000703

**Comment by ai** [comment]
Update `caniuse-lite`.

**Comment by jitendravyas** [comment]
How to update it I don't have `caniuse-lite in my main package.json? and why doesn't the tool itself update the dependencies?

**Comment by ai** [comment]
1. `npm update`
2. On every release I update dependencies. There was release, so no updates.

**Comment by jitendravyas** [comment]
ok but as I pointed out before. even here Edge 16 not showing http://browserl.ist/?q=last+3+Chrome+versions%2C+last+3+Firefox+versions%2C+last+3+Safari+versions%2C+last+3+Edge+versions%2C+last+3+Opera+versions%2C+last+3+ChromeAndroid+versions%2C+last+3+FirefoxAndroid+versions%2C+last+3+iOS+versions%2C+last+3+Samsung+versions

**Comment by ai** [comment]
Open issue in `caniuse-lite`
