### ISSUE TITLE
Query to include unreleased versions

### ISSUE THREAD

**Issue by bhollis** [ai/browserslist#163]
I'm trying to use browserslist to show an "unsupported browser" warning for folks who are using browsers that fall outside my configured list. My list looks like "last 2 Chrome versions", etc. and I'm using it to power babel-preset-env and autoprefixer, and it nicely tracks releases. However, users on unreleased versions of browsers (Chrome Canary, etc) fall outside of the list of browsers returned by browserslist. Is there a way I can include these browsers in my query?

**Comment by ai** [comment]
Good case. Right now there is no solution.

Do you have ideas of syntax?

**Comment by bhollis** [comment]
Hmm, that's tricky. Maybe to keep it consistent it could be ">= last 2 chrome versions"?

-Ben

**Comment by ai** [comment]
It is hard to understand the meaning of `>=` in this case.

What do you think about `unreleased chrome versions` or `future chrome versions`?

**Comment by bhollis** [comment]
That could be good too! In that case I'd use two queries per browser, like "last 2 chrome versions", "unreleased chrome versions". 

-Ben

**Comment by ai** [comment]
Done 29ccace

**Comment by ai** [comment]
Released in 2.3

**Comment by bhollis** [comment]
Amazing! Thanks!
