### ISSUE TITLE
Suggestion: Use cosmiconfig instead of custom config loading

### ISSUE THREAD

**Issue by swernerx** [ai/browserslist#164]
I was wondering whether it wouldn't make sense to use something more universal like "cosmiconfig" to load the browserslist configuration. They already support looking up config in package.json and via different "rc" formats. They also support config files to have a file extension (useful for e.g. correct syntax highlighting).

**Comment by ai** [comment]
I live cosmiconfig 👍 but it didn't work with custom Browserslist syntax, so it will not be really helpful.

Changing syntax is not a good step right now, because it will not take users happy 😅

**Comment by swernerx** [comment]
What about when we add TOML support to cosmiconfig? After all it's the same format, isn't it?

**Comment by swernerx** [comment]
Thanks for the consideration :)

**Comment by ai** [comment]
TOML is key-value format. Its parser can't parse current Browserslist format.

**Comment by thasmo** [comment]
Would love to see `cosmiconfig` support added.
