### ISSUE TITLE
Can't exclude QQAndroid and UCAndroid

### ISSUE THREAD

**Issue by ozio** [ai/browserslist#166]
My `.browserslistrc`:

```
last 2 version
not QQAndroid > 0
not UCAndroid > 0
```

CLI returns (`./node_modules/autoprefixer/node_modules/browserslist/cli.js --config=".browserslistrc"`):

```
and_chr 59
and_ff 54
and_qq 1.2
and_uc 11.4
android 56
android 4.4.3-4.4.4
baidu 7.12
bb 10
bb 7
chrome 59
chrome 58
edge 15
edge 14
firefox 54
firefox 53
ie 11
ie 10
ie_mob 11
ie_mob 10
ios_saf 10.3
ios_saf 10.0-10.2
op_mini all
op_mob 37
op_mob 12.1
opera 46
opera 45
safari 10.1
safari 10
samsung 5
samsung 4
```

I have tried to use `not and_qq > 0` and `not and_uc > 0`, but it does not work too.

autopefixer 7.2.1 / browserlist 2.2.2

**Comment by ozio** [comment]
The same thing with Baidu.

**Comment by ai** [comment]
You can use `last 1 QQAndroid version` as a temporary solution.

I will try to look into this problem in Friday.

**Comment by thorn0** [comment]
Same with `not ie 10`. It's simply ignored.

**Comment by ozio** [comment]
@thorn0 looks like you have another problem. `not ie 10` works pretty well: http://browserl.ist/?q=defaults%2C+not+ie+10.

**Comment by ai** [comment]
@thorn0 you must to pass some query before any `not`-query.

OK< I will add warning for this case, too many people made this mistake.

**Comment by ai** [comment]
@thorn0 hm, I already have warning for `not`-query without query before. What was your browsers query exactly and what tool do you use?

**Comment by ai** [comment]
Released in 2.3.2

**Comment by thorn0** [comment]
@ai I'm using grunt-postcss:

```js
postcss: {
    options: {
        processors: [
            require('autoprefixer')({
                browsers: '> 2%, last 2 versions, Android 4, not ie 10, Firefox ESR'
            })
        ]
    },
    dist: {
        src: '<%= files.distDir %>/built.css'
    }
}
```

**Comment by ai** [comment]
@thorn0 everything is good http://browserl.ist/?q=%3E+2%25%2C+last+2+versions%2C+Android+4%2C+not+ie+10%2C+Firefox+ESR

Maybe you want to remove IE  Mobile? It is different browser right now.

**Comment by thorn0** [comment]
No, I want to remove IE 10. I want to get rid of `display:-ms-flexbox` in my CSS, but I can't, Autoprefixer keeps adding it. Is it because of IE Mobile?

**Comment by ai** [comment]
@thorn0 yeap, IE 10 Mobile uses `-ms-` prefix too http://caniuse.com/#feat=flexbox

**Comment by thorn0** [comment]
Would be really great if `> 2%` and `last 2 versions` were combined as AND, not OR.

**Comment by ai** [comment]
@thorn0 don’t speak about different issues in non-relevant issue ;).

If you want new syntax — open new syntax with the suggestion.
