### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by glenster75** [ai/browserslist#167]
npm install browserslist

npm ERR! Unexpected end of input at 1:16526
npm ERR! browserslist":"./cli.js"},"directories":{},"dist":{"shasum":"f9251e5c
npm ERR!                                                                      ^

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2017-08-09T15_39_19_730Z-debug.log

2082 silly fetchPackageMetaData error for browserslist@^1.7.6 Unexpected end of input at 1:16526
2082 silly fetchPackageMetaData browserslist":"./cli.js"},"directories":{},"dist":{"shasum":"f9251e5c
2082 silly fetchPackageMetaData                                                                      ^
2083 verbose stack SyntaxError: Unexpected end of input at 1:16526
2083 verbose stack browserslist":"./cli.js"},"directories":{},"dist":{"shasum":"f9251e5c
2083 verbose stack                                                                      ^
2083 verbose stack     at Object.parseJSON (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
2083 verbose stack     at parse (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
2083 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
2083 verbose stack     at <anonymous>
2083 verbose stack     at process._tickCallback (internal/process/next_tick.js:169:7)
2084 verbose cwd /Users/glen/Projects/pdfTest
2085 verbose Darwin 17.0.0
2086 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
2087 verbose node v8.0.0
2088 verbose npm  v5.3.0
2089 error Unexpected end of input at 1:16526
2089 error browserslist":"./cli.js"},"directories":{},"dist":{"shasum":"f9251e5c
2089 error                                                                      ^
2090 verbose exit [ 1, true ]

**Comment by ai** [comment]
Strange. I installed latest Browserslist right now without any problem.

Seems like you had network and npm problem. Try to use latest npm@5 or yarn.
