### ISSUE TITLE
Feature Request: last X major versions queries

### ISSUE THREAD

**Issue by oigewan** [ai/browserslist#169]
While the `last X versions` query works quite well for most browsers, iOS and Safari are a bit different.  Since the browser version is still tied to the OS version, and some users are unable to install new versions of the OS on older devices, we'd like to be able to support the last two major versions of the iOS and Safari browsers.  While this is possible by manually specifying the minimum version (ie `Safari >= 8`), I thought it might be nice to be able to build a query that allows us to do this without having to remember to update our browserslist file.

**Comment by ai** [comment]
Released 2.4
