### ISSUE TITLE
Specify browserslist config file through an environment variable

### ISSUE THREAD

**Issue by moll** [ai/browserslist#17]
Hey,

As per https://github.com/postcss/autoprefixer/issues/420:
I find clogging up the project root with dozens of config files is a little shabby. Browserslist takes an env variable for setting the list. A similar variable for setting the file to read would be useful.

**Comment by ai** [comment]
Hm. We can add `BROWSERSLIST_PATH` env.

But maybe `BROWSERSLIST` env with browsers is better?

**Comment by moll** [comment]
Well, one _can_ set `BROWSERSLIST=$(cat "$BROWSERSLIST_PATH")` in theory...
I dunno. Probably both wouldn't be bad given that so many other tools provide a way to set their RC file via an env variable.

**Comment by moll** [comment]
I actually tried the above with:

```sh
BROWSERSLIST=$(cat ./config/browserslist) ./node_modules/.bin/autoprefixer -i
```

I'm still not getting the proper output that I do when I move `./config/browserslist` to the root. Am I doing this right?

**Comment by ai** [comment]
Nope. `BROWSERSLIST` accepts `chrome 10, ie 5` with commas.

You not use `./config/browserslist` in your case. Better add some variable and use it in build tool.

**Comment by moll** [comment]
Ah, that's.. a little inconsistent. I'd rather have a proper file with comments etc. if possible, so I take it that leaves only the path variable proposal as the solution?

**Comment by ai** [comment]
OK. I will add `BROWSERSLIST_PATH` var.

**Comment by ai** [comment]
`config` option was added 7cfb7f8

**Comment by ai** [comment]
`BROWSERSLIST_CONFIG` was added too 2e3c919

**Comment by moll** [comment]
Can confirm it works. Thanks!
