### ISSUE TITLE
Unknown browser query `>1% in alt-AS`

### ISSUE THREAD

**Issue by greggb** [ai/browserslist#172]
This is a query right off the README. It seemed to work fine when passing it to babel or autoprefixer directly, but once I swapped to browserslist in my package.json I get the following error:

`Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown browser query '>1% in alt-AS'`

My config is:
`
  "browserslist": [
    ">1% in alt-AS",
    ">1% in US"
  ]
`

Am I missing something obvious?

**Comment by ai** [comment]
I tested and it works http://browserl.ist/?q=%3E1%25+in+alt-AS

Maybe you have old Browserslist?

**Comment by greggb** [comment]
It works on the web, but not the config in my package.json. I just installed browserslist this morning. I'll try to poke around, but it's very strange.

**Comment by ai** [comment]
Check Browserslist version[s] by:

```
npm ls | grep browserslist
```

**Comment by greggb** [comment]
Yea, I must have something outdated in my cache. Just ran a minimal test case and it worked fine. Thanks for taking time to help.
