### ISSUE TITLE
" You can add not to any query." Is this work?

### ISSUE THREAD

**Issue by lfire** [ai/browserslist#173]
Something is wrong with not query key, and the the message like this:

> BrowserslistError: Write Any Browsers Query (For Instance, `Defaults`) Before `Not Ie <= 8`

vist the url : http://browserl.ist/?q=not+ie+%3C%3D+8

**Comment by ai** [comment]
@lfire read warning message ;).

`not` query removes browsers from *previous* queries. You don’t have previous queries.

**Comment by lfire** [comment]
@ai Sorry, but it can work before, so I don't read the message seriously.
