### ISSUE TITLE
Get browsers coverage against custom data

### ISSUE THREAD

**Issue by Poky85** [ai/browserslist#174]
I have browsers lists defined. I'd like to know coverage of these browsers in my custom data, not in selected country.

Calling this
```
let stats = {...}; // custom data
let coverage = browserslist.coverage(
	browserslist("Last 2 versions, >= 0.3% in my stats, IE >= 8, iOS >= 7", {
		stats,
	})
)
```
means "give me global coverage of browsers defined by query".

Is there any way to calculate coverage against custom data?

**Comment by ai** [comment]
It is very easy to calculate it by stats object. Few lines of code.

I am not sure that this feature is really popular to add it to the core.

**Comment by Poky85** [comment]
@ai Thank you.

Yes, it's easy :-). Here is how to do it:

```javascript
const browserslist = require("browserslist");
const stats = require("./browserslist-stats.json");

const query = "Last 2 versions, >= 0.3% in my stats, IE >= 8, iOS >= 7";
const browsers = browserslist(
	query,
	{
		stats: stats,
	}
);

// Get supported browsers coverage (relative to my stats)
let coverage = browsers.reduce(
	(coverage, browserString) => {
		const split = browserString.split(" ");
		const name = split[0];
		const version = split[1];
		const share = stats.dataByBrowser[name][version];

		return coverage + share;
	},
	0
);
console.log(coverage);
```

**Comment by ai** [comment]
We added special options for it https://github.com/ai/browserslist#coverage
