### ISSUE TITLE
Add `Baidu` browser to docs in `Browsers` section

### ISSUE THREAD

**Issue by evilebottnawi** [ai/browserslist#175]
Seems we already support query `Baidu >= 7.12` (and other), but no information about this in docs, thanks!

**Comment by ai** [comment]
@evilebottnawi sure! Do you want to send PR?

**Comment by ai** [comment]
Done b968613

**Comment by ai** [comment]
Also, I added test to keep this list actual in the future 3da9c02

**Comment by evilebottnawi** [comment]
@ai thanks, there is absolutely no time for PR :disappointed:
