### ISSUE TITLE
Is there any query for selecting all released browsers?

### ISSUE THREAD

**Issue by aleen42** [ai/browserslist#176]
I have used `defaults` and I found that the list of browsers queried out does not include IE 6-8. Is there any query word like `all` to query all released browsers?

**Comment by ai** [comment]
Short answer: `> 0%`.

Full answer: I think you don’t need all browsers. It is bad practice and there are only a few cases when it should be used. In your case `defaults, IE > 6` is better.

**Comment by aleen42** [comment]
Thanks for your reply!~
