### ISSUE TITLE
Clarification that Browser Version is needed for browserslist entry needed

### ISSUE THREAD

**Issue by Volker-E** [ai/browserslist#18]
It's not clearly stated, that every browser entry needs also either a percentage or a version to be included.
I thought of including `Firefox` only to have all possible `-moz` browser vendor prefixes included.

**Comment by ai** [comment]
I can add note to [Queries](https://github.com/ai/browserslist#queries) section.

**Comment by ai** [comment]
BTW, why you need **all** `-moz-` prefixes?

**Comment by Volker-E** [comment]
The question isn't why, but why not? :)

In contrast to default `> 1%`:
Why should I exclude possible 0.5% of my visitors (which at 100.000 visitors might be still up to 500 people) from nicest experience -- just in order to save 2KB of a 70KB CSS stylesheet? It should be easily doable and an option for the devs.

**Comment by ai** [comment]
Because main idea of Auutoprefixer is to add only actual prefixes. You should not need Can I Use data to insert all possible prefixes.

**Comment by Volker-E** [comment]
Why not? Because of unreliability of Can I Use data? Works well for me, if I use `Firefox > 0%` and saves me enormous amount of work.

**Comment by ai** [comment]
Because your CSS is bigger without any logical reason.

**Comment by ai** [comment]
Use `Firefox > 0`.

`Firefox > 0%` have no sense. Queries section doesn’t have this query.

**Comment by Volker-E** [comment]
I layed-out my reasoning above, 2KB in 70KB CSS file size. That's a trade-off I'm absolutely willing to make for 500 people. No worries, I'll save the 2KB at compressing my image files to the fullest.

**Comment by ai** [comment]
This 2KB has no reason. Does any of this 500 users use Firefox 1? Does your JS even work with Firefox 1?

**Comment by Volker-E** [comment]
Look for example into [CSS linear-gradients](http://caniuse.com/#feat=css-gradients)

You've got (Firefox only) 0.5% share of all browsers globally with `-moz` prefix (w. Chrome's prefixed it's already over 1% of all visitors). Why should I lock them out from better experience? Just to save 2KB? Especially if I don't have to invest work, because Autoprefixer with browserslist does that for me?

And yes, I try to provide a non-JS functional version with all the contend and maximized CSS-only design to be consumed by any browser (remember Any Browser campaign back in the days with sites just designed for IE).

**Comment by Volker-E** [comment]
@ai Do you still plan to put a note into queries section?

**Comment by ai** [comment]
We already has a list of possible queries abd there is no version-less query.

But small note is not difficult, maybe I really should.

**Comment by Volker-E** [comment]
It might be an edge-case, but some (including me) would appreciate it.

**Comment by ai** [comment]
Like this: 098a4d9

Maybe you can fix my English?
