### ISSUE TITLE
reaching 100% coverage

### ISSUE THREAD

**Issue by Announcement** [ai/browserslist#183]
In response to https://twitter.com/AnnounceSuccess/status/920726136371531777

# input: `>=0%`
> output: `Global coverage:98.24%`

## problems
- impossible to get to 100%

# input: `>0%`
> output: `Global coverage:98.24%`

## problems with this:
- it shows values that are exactly 0%, so I would recommend either fixing that or rounding properly.
- implies `>` is the same as `>=`

# notes
in the wild i realize that this is totally impractical, but it is still definitely an issue.

**Comment by ai** [comment]
Thanks for the report. Sorry, I will have time to investigate it only after my talk on ReactiveConf. I will try to check it in the bigging of November (seems like it is not urgent).

**Comment by Semigradsky** [comment]
Some investigation from me.

Usage global from `caniuse-lite`:
> and_chr: 29.8828
and_ff: 0.090416
and_qq: 0
and_uc: 7.65145
android: 1.6331384
baidu: 0
bb: 0.11302
chrome: 26.926787
edge: 2.096217
firefox: 5.876866000000001
ie: 3.6537610999999997
ie_mob: 0.3221073
ios_saf: 10.0248643
op_mini: 2.80843
op_mob: 0.0111391
opera: 1.115797
safari: 2.335338
samsung: 3.70141

In total it's `98.2435412`

**Comment by Announcement** [comment]
@ai definitely not urgent, just a minor quirk.
enjoy the conference :p

**Comment by peterjwest** [comment]
caniuse actually state that some browsers are excluded: http://caniuse.com/usage-table, a total of 1.6%

**Comment by ai** [comment]
@peterjwest thanks! So we can close issue.
