### ISSUE TITLE
Full browser names

### ISSUE THREAD

**Issue by peterjwest** [ai/browserslist#187]
Could the full browser names be included as an option in the API?

I'm using it to export human readable browser names, I have taken the list from the README and added them to my code, but it would be better if my code wasn't strongly coupled to this package.

I'd be happy to make a PR if you would accept it.

**Comment by ai** [comment]
We can add `browserslist/names` so if users don't need it it will not require it.

Feel free to save PR to save your name in project history.

**Comment by ideadapt** [comment]
FYI: looks like www.browserl.ist is already having some mapping function in place. (found at https://css-tricks.com/browserlist-good-idea/)

**Comment by peterjwest** [comment]
Thanks, I'll see if I can use the same data

**Comment by ai** [comment]
Seems nobody really needs it. If somebody will need, please send PR with `browserslist/names` file with code→name object.
