### ISSUE TITLE
Cannot use CLI with package.json

### ISSUE THREAD

**Issue by peterjwest** [ai/browserslist#188]
I would expect to be able to use default browerslist parameters with `browserslist` on the command line, however the cli script doesn't work without parameters, nor does it accept package.json as a valid config file.

The only way I have managed to get this behaviour is to call `browserslist --config` which seems like a bit of a hack.

**Comment by ai** [comment]
Sure! Good point. I will add some API, but only on next week (I having ReactiveConf on this week).

**Comment by peterjwest** [comment]
Thanks!

**Comment by ai** [comment]
Done 6a9fbe4

**Comment by ai** [comment]
Released in 2.6
