### ISSUE TITLE
"> 1% in IL" returns 0.09%, etc.

### ISSUE THREAD

**Issue by laukstein** [ai/browserslist#195]
http://browserl.ist/?q=%3E+1%25+in+IL, also in CLI
```
> browserslist "> 1% in IL"
Chrome for Android 62 (27.78% global usage)
Chrome 60 (1.15% global usage)
Chrome 59 (0.29% global usage)
Chrome 49 (0.99% global usage)
Edge 15 (1.62% global usage)
Firefox 54 (0.09% global usage)
IE 11 (3.22% global usage)
iOS Safari 11 (5.30% global usage)
iOS Safari 10.3 (3.60% global usage)
```
Chrome 59, Chrome 49 and Firefox 54 mustn't be listed here.
The same issue is also for `> 1% in US`, etc.

**Comment by ai** [comment]
The problem if in the difference between CLI and website?

Website is not official and have outdated Can I Use database.

**Comment by laukstein** [comment]
@ai No, it is a bug in [browserslist](https://github.com/ai/browserslist)

**Comment by ai** [comment]
Oh, I see.

Why you wrote `global usage` if you use IL usage statistics?

**Comment by laukstein** [comment]
It is probably another bug in `browserslist`. Try by yourself to run `browserslist "> 1% in IL"`.

**Comment by ai** [comment]
@laukstein 

```
➤ browerslist "> 1% in IL"
and_chr 61
chrome 60
chrome 59
chrome 49
edge 15
firefox 54
ie 11
ios_saf 11
ios_saf 10.3
```

You can switch county on Can I Use and check Israel usage statistics for every version. Israel user statistics will be different from global use statistics.

**Comment by ai** [comment]
Here is Israel usage statistics for each browser:

```
and_chr 61 — 30.6%
chrome 60 — 26.3%
chrome 59 — 9%
chrome 49 — 1.41%
edge 15 — 1.03%
firefox 54 — 1.82%
ie 11 — 4.12%
ios_saf 11 — 5.79%
ios_saf 10.3 — 3.92%
```

**Comment by laukstein** [comment]
@ai, why `browserslist "> 1% in IL"` doesn't show percentage for IL but global? Is't it an issue?

**Comment by ai** [comment]
`browserslist` CLI tool doesn’t show percentage. Here is my output:

```
➤ browerslist "> 1% in IL"
and_chr 61
chrome 60
chrome 59
chrome 49
edge 15
firefox 54
ie 11
ios_saf 11
ios_saf 10.3
```

Where did you find global usage percentage?

**Comment by ai** [comment]
[browserl.ist](http://browserl.ist) is not official website. You need to open an issue there since I don’t have any connection to its developer.

**Comment by laukstein** [comment]
I see those results by running in cmd `browserslist "> 1% in IL"`
Here my packages
```
>npm list -g --depth=0
+-- browserify@14.4.0
+-- browserslist-cli@1.0.9
...
```

My ...\node_modules\browserslist\package.json links to this repository

**Comment by ai** [comment]
Wow. Never know about `browserslist-cli`.

Here is repo. You can ask question there: https://github.com/topaxi/browserslist-cli

But also you don’t really need browserslist CLI for simple cases. `browserslist` package already have CLI tool (with same name :().

**Comment by ai** [comment]
Ouh. I already added issue to this project, but author ignored it :( 

https://github.com/topaxi/browserslist-cli/issues/3

**Comment by laukstein** [comment]
```
> npm uninstall -g browserslist-cli
removed 12 packages in 0.955s

> npm install -g browserslist
+ browserslist@2.9.0
added 3 packages in 4.282s

> browserslist "> 1% in IL"
and_chr 62
chrome 60
chrome 59
chrome 49
edge 15
firefox 54
ie 11
ios_saf 11
```

Right, I get confused with [topaxi/browserslist-cli](https://github.com/topaxi/browserslist-cli)
