### ISSUE TITLE
queries should not be whitespace sensitive

### ISSUE THREAD

**Issue by jasonkarns** [ai/browserslist#196]
- `"last 2 versions, not IE 10"` - works
- `"last 2 versions , not IE 10"` - breaks

Before parsing (presumably after splitting), queries should be `trim`d so that benign whitespace doesn't break everything.

**Comment by ai** [comment]
:+1: I will fix it on this weekend

**Comment by jasonkarns** [comment]
sweet!

**Comment by ai** [comment]
Done ca62dcf

**Comment by ai** [comment]
Released in 2.9.1.
