### ISSUE TITLE
Shareable browserlist packages

### ISSUE THREAD

**Issue by robwierzbowski** [ai/browserslist#197]
### Problem

At our company we have a number of applications that use tools that consume a browserlist. We'd like to share browserlist configurations between them.

### Proposed solution

1. Developers store browserlist.json in an npm module.
2. Browserlist and related tools expose method for reading browserlist from installed npm module.

### Possible patterns to model

ESLint shareable configs: https://eslint.org/docs/developer-guide/shareable-configs

**Comment by ai** [comment]
https://github.com/ai/browserslist#shareable-configs

**Comment by robwierzbowski** [comment]
Oh my, thank you. Not sure how I missed that. 🙇🏻‍♂️

**Comment by Iyashi** [comment]
Yet, relative paths are not working.
