### ISSUE TITLE
Safari query not working

### ISSUE THREAD

**Issue by CharliePops** [ai/browserslist#203]
Adding **Safari** as query is not working.

I am adding the query in the package.json:

```json   
 "browserslist": [
    "last 2 versions",
    "Safari",
    "iOS",
    "ie >= 10",
    "Edge"
  ]

```

and I receive: `browserslist: Unknown browser query 'Safari'`

**Comment by CharliePops** [comment]
Oh, I see I need to add a version to make it work.

**Comment by Semigradsky** [comment]
But why? If 'Edge' without version is working.

**Comment by ai** [comment]
@Semigradsky `Edge` query doesn’t work
