### ISSUE TITLE
Documenting unofficial package.json fields

### ISSUE THREAD

**Issue by stereobooster** [ai/browserslist#204]
Hey. First of all thank you very much for this awesome project.

I'm [collecting documentation about unofficial package.json fields](https://github.com/stereobooster/package.json). Browserslist is one of them. By any chance do you know any source where I can find more such projects? Maybe RFC repository?

Thanks

**Comment by ai** [comment]
Wow. You start a great collection.

Sorry, there is no any rules about unofficial fields. I saw many different format of field names. Like `babel`, but `eslintConfig`.

I recommend to add `stylelint` and `jest`. Also I will promote your list in my Twitter and ask friends to send PR with other fields (you want all of them or you have criteria?)

**Comment by stereobooster** [comment]
Thanks a lot))
