### ISSUE TITLE
idea: browserslist for npm packages

### ISSUE THREAD

**Issue by stereobooster** [ai/browserslist#205]
The current implementation of browserslist good fit for applications, but is it a good fit for libraries?

I'm thinking out loud. https://github.com/ai/browserslist/issues/75 wants to add node.js support. Same time there is `engines` in package.json. Should `engines` directive allow to list browsers?

Like:

```json
{
  "engines": {
    "Firefox": "> 20",
    "not ie": "<= 8"
  }
}
```

Can this information be used by browserslist to verify that all required packages met application browser requirements?

**Comment by ai** [comment]
I like this idea. Maybe not in Browserslist directly, but as some addition tool on top of Browserslist queries.

**Comment by michael-ciniawsky** [comment]
Unofficial, but the widely used `package.browser` (version of the package transpiled/written with changes for browser usage) property would also be nice to 'support' as mixture of `package.engines` && `browserslist` somehow :). Though this is not really `browserslist` issue 🙃  

```js
{
   name: "",
   version: "",
   module: 'path/to/esm.js', // (Source Code)
   // e.g babel-preset-env (targets via browerslist)
   main: 'path/to/cjs.js', // engines.node 
   browser: 'path/to/browser.js', // engines.browsers
   engines: {                                                                                        
     node: ">= 4",
     browsers: { 
        ...list
     }
  }
}
```

**Comment by stereobooster** [comment]
@michael-ciniawsky there is an issue with `browser` field - how to support `module` and `browser` simultaneously. Options:
- browser-module https://github.com/webpack/webpack/issues/4674
- `esm: true` https://github.com/nodejs/node-eps/pull/60

I'm collecting package.json fields, if you are interested https://github.com/stereobooster/package.json

> Maybe not in Browserslist directly, but as some addition tool on top of Browserslist queries.
@ai yes definitely, was rather interested in your opinion

Also worth to note that browserslist queries tend to have moving target, like "2 last versions of browse", but engines queries should be more static, like "Chrome >= 48 or Firefox >= 50".

**Comment by michael-ciniawsky** [comment]
> I'm collecting package.json fields, if you are interested https://github.com/stereobooster/package.json

 👍 

@stereobooster The `pkg.browser` field should definitely be unofficially 'specced' by some entity and at best officially by `npm`. E.g please not **another** field for the **same** purpose, it's very bad practice to do that imho :) (no offense to anyone here). Why not `pkg.browser.module = {String}  && pkg.browser.script = {String}` with or simply an `{Object}`

```js
// ESM 
pkg.browser = { src: 'path/to/module.js', type: "module" }
// Script
pkg.browser = { src: 'path/to/script.js' }
``` 
to start with the basics?

```js
pkg.browser = {
  type: 'module', // If omitted => script
  src: 'path/to/script.js', // I'm mandatory
  custom: 'option' // I'm not mandatory (webpack, rollup, ... Options)
  // ...add what you like to the {Object} (import.meta Style)
}
```
But we derailing the issue here... 😛

**Comment by stereobooster** [comment]
Moved issues to another tracker (https://github.com/stereobooster/package.json/issues/4, https://github.com/stereobooster/package.json/issues/2), because, indeed, this is not Browserslist issue. Thank you for your comments

**Comment by jskrzypek** [comment]
> The pkg.browser field should definitely be unofficially 'specced' by some entity and at best officially by npm

@michael-ciniawsky FWIW there's already this: https://github.com/defunctzombie/package-browser-field-spec
