### ISSUE TITLE
Cannot find module 'process'

### ISSUE THREAD

**Issue by thomgray** [ai/browserslist#210]
I've had a issue with the recent version of `browserlist` (v2.11.0) when using `babel-presets-env` on node v.0.12.9

we are getting the following warning when running with grunt-babel
```shell
Warning: Cannot find module 'process' (While processing preset: ".../node_modules/babel-preset-env/lib/index.js")
```
Everything works fine when I upgrade to node v.4.

Including v.2.8.0 in my package dependencies fixes the warning, which I could do going forward. Just though I would raise the issue here in case you hoped to continue support for legacy node versions.

Thanks

**Comment by ai** [comment]
@thomgray sorry, Node.js 0.12 is not supported [anymore](https://github.com/nodejs/Release) :(. Node Foundation doesn’t support Node.js 0.12 since 2016.

I highly recommend updating to Node.js 4 or 8. Node.js 0.12 doesn’t have security fixes anymore, so it is dangerous to use it.

**Comment by thomgray** [comment]
@ai No worries, we can use the workaround until someone decides to upgrade out internal frameworks ⏳ 

Cheers
