### ISSUE TITLE
v2.10.0 broke node 0.12

### ISSUE THREAD

**Issue by ljharb** [ai/browserslist#211]
https://github.com/ai/browserslist/commit/c7e79cc1a4dd99c8a6a9efe86f03d16c4c704de2 seems to have [broken](https://travis-ci.org/airbnb/hypernova/jobs/328517578) node 0.12 by way of babel-preset-env.

`process` isn't a core module, so it shouldn't be required - browserify and webpack both should be providing their own polyfill for it.

**Comment by ai** [comment]
Hi. We didn't support Node.js 0.12 since Browserslist 2.0.

Also even Node Foundation doesn't support Node.js 0.12 https://github.com/nodejs/Release

This is why I highly recommend to update Node.js, since 0.12 doesn't have security updates anymore. It is dangerous to use it.

**Comment by ai** [comment]
Is `process` module part of Node.js >= 4?

**Comment by ai** [comment]
I requested `process` to use `package.browser` and disable `process` polyfill in webpack/browserify.

Do you know a different way to do it?

**Comment by ai** [comment]
I think I found a way to remove `require('process')` =^_^=. Also, it will fix #199 

@ljharb but I need to be sure, that `require('process')` is bad practice for Node.js >= 4.

**Comment by ljharb** [comment]
What node core supports is not necessarily related to what libs support, but it's more that something that worked in 2.x, stopped working in 2.10, which imo qualifies as a semver-major, regardless of officially supported platforms.

As far as "bad practice", i'm not really sure, but `process` is a global, and i've never seen `require('process')` ever used before.

If browserslist specifically needs code changes for browsers (webpack or browserify), i'd expect the "browser" field in your package.json to point to a browser-specific entry point, instead of changing the node code.

**Comment by ai** [comment]
SemVer guarantees are related only for public API. Browserslist 2.0 “public API” supported only Node.js >= 4. So any changes for Node.js < is not part of public API. It could be fixed or broken in any minor release, since there is no any guarantees for Node.js 0.12.

This is how I interpreted SemVer 😏.

**Comment by ljharb** [comment]
Certainly it's a subjective part of semver, unfortunately.

Either way, if you *are* able to fix it, that would be greatly appreciated, even if it's by happenstance while fixing something else :-)

If not, I'll try to get a `babel-preset-env` published that pegs browserslist to `=2.10.0`.

**Comment by ai** [comment]
Done 03c72ca

**Comment by ai** [comment]
Released in 2.11.2

**Comment by ljharb** [comment]
Thank you!!
