### ISSUE TITLE
Make electron-to-chromium dependency optional

### ISSUE THREAD

**Issue by joshas** [ai/browserslist#213]
electron-to-chromium package includes electron-releases package with 8MB json data file. I suppose only few developers actually need it. Could this dependency become optional?

**Comment by ai** [comment]
Yeap, 8 MB is a problem. But real solution is to reduce `electron-to-chromium` size.

@kilian can you look why `electron-to-chromium` is so big? Just install it to new project and look into `node_modules`. Do you have `.npmignore` to remove development files from npm package?

**Comment by Kilian** [comment]
The latest version has electron-releases as a devDependency: https://github.com/Kilian/electron-to-chromium/commit/0d1fb01d0f52044958c8fa5ce2972a94885336f1  but it doesn't have a new npm version yet (those are only triggered for new electron versions). I'll make a new one in a moment.

**Comment by Kilian** [comment]
v1.3.31 was just released containing this! https://www.npmjs.com/package/electron-to-chromium

**Comment by willnode** [comment]
I just made a PR for this.

**Comment by ai** [comment]
Done, size of `electron-to-chromium` was dramatically reduced.
