### ISSUE TITLE
Inheritable configuration

### ISSUE THREAD

**Issue by kettanaito** [ai/browserslist#216]
Hello.

I am publishing a library, and I would like it to behave the following way:
* Inherit browserlist specification if it's present in the project my library is used
* Otherwise, use a fallback browserlist defined within the library

Could you please advise me the recommended way of doing so?
Thank you.

**Comment by ai** [comment]
Hm. Interesting question!

I will think about perfect solution. Maybe we should add `default` option.

But there is a thing that I am worry about. If you will have different defaults, target browsers for your tool will be different to Autoprefixer target browsers (in case when user doesn't have own Browserslist config). Is it OK?

Could you tell me more about your tool land why you want to change defaults?

**Comment by kettanaito** [comment]
Thanks for a quick reply!

Primarily, I think it would be good for the target project to specify which browsers its solutions should support. If each library has its own browserlist, there is a chance it will be different from what a project is aiming to cover.

As an example, I am writing a Form library, and currently I use my custom browserlist declaration within the `.babelrc` of *my library* (using `babel-preset-env`). I cannot assume which browsers the end project is going to cover, the project which will have my Form library installed as dependency and bundled.

Hopefully, I am making myself clear.

**Comment by ai** [comment]
You use Browserslist for babel-preset-env? In this case babel-preset-env will be executed only on npm publish.

Users of your library will not be able to change browsers for your babel-preset-env (by default, user's Babel will not process node_modules).

This is why I recommend to use Browserslist default target browsers since they are safe for any users.

**Comment by kettanaito** [comment]
@ai I see. Yes, you are right.

Could you please advise me if there is a technical way to achieve what I am describing?

**Comment by ai** [comment]
I don't see a good way here ☹️

You can ask developers to run Babel on your plugin. But it will be not really useful (nobody read docs).
