### ISSUE TITLE
What about Vivaldi?

### ISSUE THREAD

**Issue by dpm39560** [ai/browserslist#220]
What about the new Vivaldi browser? It does not seem to be on the BrowserList.

This browser is rapidly taking over a large segment of the browser market and should be included.

Check out https://vivaldi.com/

**Comment by ai** [comment]
You should ask Can I Use to add it first.

**Comment by dpm39560** [comment]
Thanks, but that’s out of my sphere of experience. Totally swamped with other tasks.

 

    DPM

**Comment by ai** [comment]
Just open the same issue in https://github.com/Fyrd/caniuse

**Comment by dpm39560** [comment]
Thanks. It’s already there.

 

   DPM

**Comment by ai** [comment]
> As a Chromium-based browser it's unlikely that Vivaldi will be included

Sad.

I subscribed to the issue. When it will be fixed in Can I Use I will be able to add a new browser to docs.

**Comment by dpm39560** [comment]
Sigh.  Thanks.
