### ISSUE TITLE
Custom Usage Data does not download correctly from Can I Use

### ISSUE THREAD

**Issue by jstrangfeld** [ai/browserslist#221]
It appears localStorage no longer contains a lookup key for `config-primary_usage` causing the snippet in README.md to download a file with the contents: `undefined`

A workaround will be required to fix the code snippet. However, it would be better if there was an "official" method of populating and downloading custom browser stats. For example, a GitHub Pages hosted application that connects to GA and loads the data into a JSON file. This would mimic the behavior found on the Can I use website, but will ensure that it is compatible with browserslist (without worrying about a third-party introduced breaking changes).

**Comment by ai** [comment]
Do you want to send PR?

**Comment by jstrangfeld** [comment]
Yes, I can do that, but I think there should also be a discussion about a long-term solution.
