### ISSUE TITLE
Unknown version error

### ISSUE THREAD

**Issue by jonathantneal** [ai/browserslist#229]
Yesterday I started noticing that projects using browserslist started throwing errors.

I was getting errors about Android, while this user gets errors about Firefox

```Unknown version 61 of firefox```

https://github.com/jonathantneal/postcss-preset-env/issues/8

**Comment by Grawl** [comment]
Same here for `android 56` from this repository readme.

**Comment by ai** [comment]
Option `ignoreUnknownVersions` was released in 3.1.0.
