### ISSUE TITLE
Is Firefox ESR a supported browser?

### ISSUE THREAD

**Issue by anilnatha** [ai/browserslist#23]
The documentation in the Readme file lists 'Firefox ESR' as a sample query, yet it is _not_ listed in the list of 'Browsers'.

1. Is 'Firefox ESR' a supported Browser?
2. if it is a supported browser, can queries be run against it like so:

        Firefox ESR > 25

**Comment by ai** [comment]
ESR is already version, so you must write `firefox esr`.

**Comment by anilnatha** [comment]
Sorry, I'm a little confused. I do not understand what you mean by "ESR is already version."

Firefox ESR is a subset of the standard FIrefox browser. And in addition, it has it's own [release schedule and release numbers](https://www.mozilla.org/en-US/firefox/organizations/faq/), just like Firefox does.  The ability to query different versions of Firefox, but not Firefox ESR is conflicting in my opinion and doesn't do justice to those that _need_ to target specific versions of Firefox ESR.

**Comment by ai** [comment]
Firefox ESR is not special build :-). Just alias for version.

**Comment by anilnatha** [comment]
I just came to that realization and was updating my comment when you posted. Thank you!
