### ISSUE TITLE
[Question] dose last 2 version exclude IE?

### ISSUE THREAD

**Issue by jimmywarting** [ai/browserslist#231]
Technically microsoft ditched IE for Edge and are no longer working on IE. 

IE become Edge... And it have been a few Edge releases after that

So when you say *"last 2 versions"* those it exclude IE?

**Comment by ai** [comment]
Nope. It requires 2 versions of every browser (Edge and IE are separated browsers according Microsoft).

User `last 2 versions, not IE > 0`. But I recommend `last 2 versions, not dead` (it removes IE 10, and will remove IE 11, when Microsoft will stop security updates for IE 11).

**Comment by jimmywarting** [comment]
Ok, thanks for clearing that up.
