### ISSUE TITLE
[Feature] 'mobile' / 'not mobile'

### ISSUE THREAD

**Issue by xavhan** [ai/browserslist#24]
Sometimes it makes sens to select browsers by being mobile or not.

`browserslist('last version');`
returns
`["chrome 43", "firefox 38", "ie 11", "ie_mob 11", "ios_saf 8.1-8.3", "opera 30", "safari 8"]`

We can imagine 
`browserslist('last version not mobile');`
returning
`["chrome 43", "firefox 38", "ie 11", "opera 30", "safari 8"]`
and
`browserslist('last version mobile');`
returning
`["ie_mob 11", "ios_saf 8.1-8.3"]`

What do you think ? 

I could try to make a PR if that makes sense to you.

**Comment by ai** [comment]
I think developing only-mobile or non-mobile versions is a very bad practice. `last 1 versions` is a best choice.
