### ISSUE TITLE
Question: Is it possible to exclude a browser from the usage % or last versions options

### ISSUE THREAD

**Issue by lambertsteven** [ai/browserslist#28]
For example, I want to support last 2 versions of all browsers *except* IE, in which case I only want to support IE 11 (so I don't get the `-ms-` options for flexbox).

**Comment by ai** [comment]
Nope, there is not such way right now.

Can you suggest some clear and simple API for this?

**Comment by lambertsteven** [comment]
Well, if we consider the browser list like a glob, then maybe mimic globs behavior to exclude files from the list using the `!` operator?

```js
browserslist('last 2 version, !ie 10');
```

**Comment by ai** [comment]
Or more universal solution:

```js
browserslist('last 2 version, not last 2 ie version, last 1 ie version');
```

**Comment by ai** [comment]
OK. I try to implement it for Autoprefixer 5.3 (I will make it after PostCSS 4.2 release).

**Comment by lambertsteven** [comment]
Sweet, thanks a lot.

**Comment by LeZuse** [comment]
:+1: Also in need of this. Usually IE is the one you want to exclude as its version 8 still satisfies the > 1% rule (sadly).

**Comment by aleross** [comment]
We have a web application that doesn't support mobile right now (there are native apps instead), so another use-case would be !mobile or !iOS

**Comment by ai** [comment]
@aleross why users can use your site from modile browsers without mobile support? Mobile browser just will use zoom.

**Comment by realityking** [comment]
This problem is aggrevated with the release of Edge. We're trying to drop IE 10, as we're counting Edge as the newest IE version but browserslist considers them as distinct browsers.

**Comment by ai** [comment]
Yeap, I want to fix it after I finish PostCSS 5.0

**Comment by realityking** [comment]
Awesome, thank you.

**Comment by ai** [comment]
Done fee338b

**Comment by lambertsteven** [comment]
Awesome! Thanks so much

**Comment by mrchief** [comment]
`last 2 version, not last 2 ie version` gives `browserslist: Unknown browser query `last 2 version, not last 2 ie version` error

**Comment by ai** [comment]
@mrchief show me your `package.json` and Browserslist config

**Comment by mrchief** [comment]
That 1 line is all I have. I tried breaking it into multiple lines but same results. 

![image](https://user-images.githubusercontent.com/781818/41049989-29114a52-6980-11e8-9362-1550fc36fc9f.png)

**Comment by mrchief** [comment]
Also, this query fails: `last 2 version, not ie`. Not sure if that's correct syntax-wise

**Comment by ai** [comment]
@mrchief you must split queries in `.browserslistrc` by new line, not by `,`

I will add a warning for missed new line in config in next week (there are no user mistakes, there is only a bad UX). But you anyway must to replace `, ` to new lines.

**Comment by mrchief** [comment]
That works.

```
last 2 version
not last 2 ie version
```

Any idea why this fails?

```
last 2 version
not ie
```

**Comment by ai** [comment]
@mrchief there is no `ie` query to use it in `not ie`. Use `not ie > 0`
