### ISSUE TITLE
Add Microsoft Edge

### ISSUE THREAD

**Issue by mzgol** [ai/browserslist#29]
Microsoft Edge is a new browser, forked from IE but that is not IE itself. Windows 10 will include both Edge & IE11.

`caniuse-db` now separates those 2 browsers, see https://github.com/Fyrd/caniuse/commit/0f31db424f056ec1b934c9788100cae69cab60f2.

The browser should be added to the list.

**Comment by ai** [comment]
Sure. I will start it after PostCSS 5.2 release.
