### ISSUE TITLE
How are browser queries combined?

### ISSUE THREAD

**Issue by marcvangend** [ai/browserslist#35]
I can't figure out, from reading the documentation, exactly how browser queries are combined when you use multiple queries.

For instance the  example query `browserslist('last 1 version, > 10%');` in README.md is explained as "last version of each major browser and versions, with a usage of over 10% in global usage statistics". I read this as: the intersection of the result sets 'last 1 version' and '> 10%'. In other words, I conclude that browsers in the final list must match *all* requirements.

However, another example in the readme reads:

    > 1%
    Last 2 versions
    IE 8 # sorry

If my conclusion above (browsers must match all criteria) is correct, then this example does not make sense because the queries "Last 2 versions" and "IE8" are mutually exclusive, so the result should be an empty list... Except that it's not when you actually test this.

It seems that some queries are AND queries, while others are OR queries. Can you explain (and add to the documentation) exactly how browserslist queries are combined?

**Comment by ai** [comment]
As "or". Try in CLI for better understand.

I am open for docs PR.
