### ISSUE TITLE
Edge versions 1 or 12?

### ISSUE THREAD

**Issue by ntwb** [ai/browserslist#37]
Throughout the docs and code base there are examples and tests documenting different versions of the Microsoft Windows 10 browser Edge, these values can be `1`, `11`, or `12`

• The original commit via https://github.com/ai/browserslist/commit/e7c56e8df8a194ed1cb74b9d3b8fbb7371927cd2 ~3 months ago in https://github.com/ai/browserslist/issues/29 all reference `edge 1`

• The commit via https://github.com/ai/browserslist/commit/e105a4aac857d5d0da2e9e21b7e00bf81f6e594e ~16 days ago uses `edge 12` in README.md and tests.js

So, should it be `edge 1` or `edge 12`?

**Comment by ai** [comment]
@ntwb Browserslist just uses data from [Can I Use](https://github.com/Fyrd/caniuse). It has `1` before and `12` right now.

**Comment by ntwb** [comment]
Thanks for the clarification Andrey, I added a PR to update the tests to match the "real world" versons and remove any traces of `edge 1` :)
