### ISSUE TITLE
Add option to specify custom analytics data

### ISSUE THREAD

**Issue by MoOx** [ai/browserslist#4]
caniuse.com UI offers this option. Maybe we should get it too. Don't you think ?

**Comment by ai** [comment]
You can already use `> 5% in US`. You ask about it?

**Comment by MoOx** [comment]
Hum. Good to know. Sorry to miss that. Renaming the issue.

**Comment by ai** [comment]
So I close issue if Browserify already can do it? :)

**Comment by MoOx** [comment]
You mean browserslist.
It cannot import custom analytics right now am I correct?

**Comment by ai** [comment]
You mean usage statistics from some country? You can do it right now by:

```js
# Take browsers used by 5% of global users, 1% of Russian and Ukrainian users
browserslist('> 5%', '> 1% in RU', '> 1% UA')
```

**Comment by MoOx** [comment]
Non I mean custom google analytics data like on caniuse.com

![screen shot 2015-01-10 at 14 54 42](https://cloud.githubusercontent.com/assets/157534/5691799/c7e692bc-98d8-11e4-8d73-2d397bbe83a4.png)

**Comment by ai** [comment]
Ouh, I understand. Yeap, we should implement it.

@Fyrd is there some examples, for you parse GA data in canisue.com?

**Comment by ai** [comment]
I suggest this API:

```js
browserslist('> 5% in my GA', { ga: gaFileContent });
```

Does '5% in my GA' sounds normal? I want some separated selector to be able to combine global statistics and your GA statistics.

**Comment by ai** [comment]
Done in https://github.com/ai/browserslist/pull/41 by @DanReyLop
