### ISSUE TITLE
Select mobile browsers with more than 5% usage

### ISSUE THREAD

**Issue by DaSchTour** [ai/browserslist#42]
I guess it's still a common scenario that there are webpages for mobile only. So I think it could be useful to have a simple query, that simply selects all mobile browsers. And additionaly they could be quried by usage. Something like "> 5% mobile in US". The same also could also be useful for desktop.

**Comment by ai** [comment]
It is a very bad practice. What if desktop user will open a mobile link?

Sorry, Browserslist provides shortcuts only for good for Internet practices.

**Comment by DaSchTour** [comment]
What if desktop user will be imediatly redirected to to the desktop shop and has no possibility to see the mobile shop? Also the mobile shop will look terrible on desktop with or without the additional prefixes that 99% of the users of the shop will not need. Most important for mobile is to have as less garbage as possible.

**Comment by ai** [comment]
First, separated versions and redirects based on user agent is a bad practices too. Use media queries.

Main problem is that there is no such thing as mobile browser. Your redirect software will detects one browsers and still not detects other. It is better to set browsers manually in your case to have same browsers in both parts.

**Comment by DaSchTour** [comment]
Okay, that's like wishing to live in utopia. And by the way. Your tool for optimizing autoprefixer also just supports the bad praxis of browsers to not follow DRY. I guess it's just that you build this tool and because of some crazy accident it is used to improve autoprefixer and now you are to lazy or not able to improve it. If I was hiding behind good practice and bad practiceat my work I could pack my things very soon.
