### ISSUE TITLE
agnostic to order in config browserlist

### ISSUE THREAD

**Issue by evilebottnawi** [ai/browserslist#43]
if i use:
```
> 1%
Explorer >= 9
not IE <= 8
```
Output (IE8 exclude!):
```bash
...
  [ 'ie', '11' ],
  [ 'ie', '10' ],
  [ 'ie', '9' ],
...
```

if i use:
```
> 1%
not IE <= 8
Explorer >= 9
```
Output:
```bash
...
  [ 'ie', '11' ],
  [ 'ie', '10' ],
  [ 'ie', '9' ],
  [ 'ie', '8' ],
...
```

**Comment by ai** [comment]
Do you have some user case where it is important?

We need a good reason to broke API.

**Comment by evilebottnawi** [comment]
@ai it was very implicitly for me and I made a mistake, if we can not change the api maybe documenting this behavior a large bold font.

**Comment by ai** [comment]
Could you send a PR for docs. Without bold font 😉.

**Comment by ai** [comment]
I make it more clear fb29a50
