### ISSUE TITLE
Define Major Browser

### ISSUE THREAD

**Issue by dleve123** [ai/browserslist#46]
The term "major browser" is used multiple times in the README, but it's never defined.

I've also poked around in caniuse.com in attempt to find a definition, but my searching has not been successful. I see there's a [test case](https://github.com/ai/browserslist/blob/ddbfa299b4f3705afafecabd9cbdacb3cf84d015/test/last.js#L48) in the project that's relevant, but I think it would be helpful to document this term more explicitly.

Hope this helps!

**Comment by ai** [comment]
PR is welcome, because I am not so good with English.
