### ISSUE TITLE
Getting browser support coverage

### ISSUE THREAD

**Issue by JoshuaWise** [ai/browserslist#51]
Hello,

I was wondering if there would be a simple way of using this package, or extending it, to input a browser query string and get a back a total percentage of users that fall within the selected browsers.

For example, I want to input `last 2 versions, ie 8-11`, and get back something like:
```
These browsers account for 96% of all users globally.
```

Would this be possible/easy?

**Comment by ai** [comment]
We can add it to `./cli.js` tool. Do you want to send PR?

**Comment by JoshuaWise** [comment]
I wouldn't know how to implement it, but in a few weeks if you or someone else isn't able to, I could take a swing at it when I have time

**Comment by ai** [comment]
First step: f574bc2ad47340778e4e95917928263103d9b055

**Comment by ai** [comment]
Second step: 6ed9903

I add `--coverage` or `-c` option to CLI.

**Comment by ai** [comment]
Third step: 5af7b11

**Comment by ai** [comment]
Done. Released in 1.2.0.

**Comment by JoshuaWise** [comment]
This is fantastic. Thanks for doing that!
