### ISSUE TITLE
JS API and CLI return different browser sets

### ISSUE THREAD

**Issue by StefanSchwartze** [ai/browserslist#58]
When I try browserslist "> 0.5%" in my cli, I get the following result:

`and_chr 50
and_uc 9.9
android 4.4
android 4.4.3-4.4.4
android 4.2-4.3
chrome 50
chrome 49
chrome 48
chrome 45
chrome 29
edge 13
firefox 45
ie 11
ie 9
ie 8
ios_saf 9.3
ios_saf 9.0-9.2
ios_saf 8.1-8.4
op_mini 5.0-8.0
opera 36
safari 9.1
safari 9`

But when I try the same with the JS API with browserslist('> 0.5%'), I get the following result:
`'and_chr 49',
  'and_uc 9.9',
  'android 4.4',
  'android 4.4.3-4.4.4',
  'android 4.2-4.3',
  'chrome 49',
  'chrome 48',
  'chrome 47',
  'edge 13',
  'firefox 45',
  'firefox 44',
  'ie 11',
  'ie 9',
  'ie 8',
  'ie_mob 11',
  'ios_saf 9.3',
  'ios_saf 9.0-9.2',
  'ios_saf 8.1-8.4',
  'op_mini 5.0-8.0',
  'safari 9'`

The difference is, that for example both sets include different chrome versions...

**Comment by ai** [comment]
@StefanSchwartze do you have same `caniuse-db` version in CLI and in JS API?

**Comment by StefanSchwartze** [comment]
@ai thanks a lot, this solved the problem.
