### ISSUE TITLE
Doesn't exclude prefixes

### ISSUE THREAD

**Issue by TrySound** [ai/browserslist#59]
`'last 10 versions', 'not ie <= 11'` doesn't exclude -ms- prefix in flexbox via autoprefixer

**Comment by ai** [comment]
```
browserslist
➤ ./cli.js 'last 10 versions, not ie <= 11'  
chrome 51
chrome 50
chrome 49
chrome 48
chrome 47
chrome 46
chrome 45
chrome 44
chrome 43
chrome 42
edge 13
edge 12
firefox 46
firefox 45
firefox 44
firefox 43
firefox 42
firefox 41
firefox 40
firefox 39
firefox 38
firefox 37
ie_mob 11
ie_mob 10
ios_saf 9.3
ios_saf 9.0-9.2
ios_saf 8.1-8.4
ios_saf 8
ios_saf 7.0-7.1
ios_saf 6.0-6.1
ios_saf 5.0-5.1
ios_saf 4.2-4.3
ios_saf 4.0-4.1
ios_saf 3.2
opera 37
opera 36
opera 35
opera 34
opera 33
opera 32
opera 31
opera 30
opera 29
opera 28
safari 9.1
safari 9
safari 8
safari 7.1
safari 7
safari 6.1
safari 6
safari 5.1
safari 5
safari 4
```

Sorry, I think problem is in your other environment. Try to run Autoprefixer alone.

Maybe webpack or some other tool after Autoprefixer add `-ms-` prefixes? Try to create `browserslist` config ti share browsers for all hidden Atuoprefixer tools.

**Comment by ai** [comment]
Feel free to Reopen if you find that standalone pure Autoprefixer has this issue,

**Comment by andykenward** [comment]
I found `ie_mob` was the reason for the `-ms-` prefixes
