### ISSUE TITLE
Feature Request: Allow overriding browsers

### ISSUE THREAD

**Issue by donaldpipowitch** [ai/browserslist#63]
Hi, I'd like to not just pass custom usage data for browsers, but also the browsers itself. 

Use case: Selenium Grids.

It would be nice, if I could use a query like `"last 2 Chrome versions"` and I'd get not the last two _released_ Chrome versions (e.g. currently `[ 'chrome 51', 'chrome 50' ]`), but the last two Chrome versions available on a specific Selenium Grid. (And my custom stats could represent _stability_ instead of _usage_ data, because Selenium can sometimes be flaky.)

Currently I could hack this together like this, but I this overrides the browsers completely, so I cannot switch between multiple uses cases:

```
// copy browserslist.data.chrome.released?
const availableChromeVersions = getAvailableVersionsFor('chrome'); // could be [ '49', '50']
browserslist.data.chrome.released = availableChromeVersions; // overrides versions
const browsers = browserslist('last 2 Chrome versions');
// restore browserslist.data.chrome.released?
```

**Comment by ai** [comment]
Why you could not use `"chrome 50", "chrome 49"?

Also you could take origin data from `browserlist.data`.

**Comment by donaldpipowitch** [comment]
> Why you could not use `"chrome 50", "chrome 49"?

You mean hard coding these values? Because I don't know what are two latest Chrome browsers supported by a specific selenium grid.

> Also you could take origin data from browserlist.data.

What do you mean with this?

I currently save the original browserslist.data, create a custom browserslist.data specific for the used selenium grid, make my query with `browserslist(query)` and restore the original 
browserslist.data. This works great, but is a little bit hacky. I can show you the source code tomorrow.

**Comment by ai** [comment]
You want to fake data for your tests? It is hacky way, anyway 😉. I can't find some good API, that I can write for you, sorry.

The best way is to use different browser requirements in production and in test. So you will be free from hacking data.

**Comment by donaldpipowitch** [comment]
No, I don't want to fake data :) I want browserslist to parse a query like "last 2 Chrome versions", but browserslist currently doesn't offer a way to specify what "last" refers to. Currently it refers to all released versions of Chrome as specified in caniuse-db. But it could "grab" the last two Chrome versions of a selenium grid, too.

I think the most recent version of Safari in caniuse-db is currently 9.1, but if I remember correctly from my research today the most recent Safari version which is supported by Sauce Labs is 9.

**Comment by ai** [comment]
What is Selenium Grid? (Sorry, I am in the middle of Kazakhstan with show Internet to use Google)

Maybe this is why I can't understand, why you could not use `last 2 versions, <some Safari version reflected to Selenium engine>` in your Selenium tests.

**Comment by donaldpipowitch** [comment]
A selenium grid is a cluster of browsers you can use to test websites. Because you can host as much or as less browsers you want or because sometimes a browser can shut down you never really know which browsers are available.
Sauce Labs is a professional cloud service which hosts a result big selenium grid.

**Comment by ai** [comment]
Selenium Grid had every version of browsers? Why you can not use just `last 2 versions` there?

**Comment by donaldpipowitch** [comment]
No it has not *every* version of a browser. Only since are supported and it is up to the developer how man many browsers her ads to the grid or not.

**Comment by ai** [comment]
OK. Why you can take browser version from Selenium Grid and put it directly to Autoprefixer like `chrome 40`?

**Comment by donaldpipowitch** [comment]
> OK. Why you can take browser version from Selenium Grid and put it directly to Autoprefixer like chrome 40?

I don't use Autoprefixer. I solely use browserslist for its parsing capabilities and I use it because I want to express relative versions like `"last 2 versions"`, because I don't want to hardcode the version numbers.

Anyway... my hack works and it is a minimal hack. Maybe we should stop here.
