### ISSUE TITLE
Should the UC Browser be highlighted in the docs?

### ISSUE THREAD

**Issue by ntwb** [ai/browserslist#64]
In updating Autoprefixer I tested browser usage `> 5%` and was surprised to see UC Browser at 6.65% of the total desktop and mobile browser usage worldwide http://caniuse.com/usage-table

I installed browserlist locally:
```shell
$ browserslist ">5%"
and_chr 51
and_uc 9.9
chrome 51
chrome 50
ios_saf 9.3
```

Though predominantly used in the Chinese market it is the #1 mobile browser in China with 34.22% ([src](http://gs.statcounter.com/#mobile_browser-CN-monthly-201506-201606-bar)) usage and 14.63% ([src](http://gs.statcounter.com/#desktop+mobile+tablet-browser-CN-monthly-201506-201606-bar)) of the total desktop, mobile and tablet market in China broken down to 75% Android and ~25% iOS.

Home page: http://www.ucweb.com/ Wikipedia: https://en.wikipedia.org/wiki/UC_Browser

Mobile Browser Usage: 

Region | Percentage | Source
------------ | ------------- | -------------
Global|17.58%|http://gs.statcounter.com/#mobile_browser-ww-monthly-201506-201606-bar
 | | 
Asia|28.67%|http://gs.statcounter.com/#mobile_browser-as-monthly-201506-201606-bar
Africa|6.72%|http://gs.statcounter.com/#mobile_browser-af-monthly-201506-201606-bar
Oceania|2.45%|http://gs.statcounter.com/#mobile_browser-oc-monthly-201506-201606-bar
South America|2.18%|http://gs.statcounter.com/#mobile_browser-sa-monthly-201506-201606-bar
EU|1.42%|http://gs.statcounter.com/#mobile_browser-eu-monthly-201506-201606-bar
North America|1.09%|http://gs.statcounter.com/#mobile_browser-na-monthly-201506-201606-bar

So the question is should the UC Browser be highlighted as a "major browser"? or maybe at least mentioned in the docs as 6.65% global usage is more than the total usage of all IE versions of 6.43%!

**Comment by ai** [comment]
Yeap, we can do it. But only in on next major release.

**Comment by ntwb** [comment]
No problem, I was quite surprised by these stats 😮
