### ISSUE TITLE
Targeting PC/Mobile-only browsers

### ISSUE THREAD

**Issue by Justineo** [ai/browserslist#67]
I've read #42 and am totally aware of why browserslist doesn't support this. In my case our website (https://www.baidu.com, I'm planning to apply Autoprefixer to some of it's search result content) does server-side redirection so mobile users actually don't have a chance to visit desktop site. So it'll be great if desktop stylesheets don't add mobile-only code.

**Comment by ai** [comment]
Just select mobile browsers manually.

I afraid that if we will have special query for mobile/desktop many bad developers will be use it in wrong cases (not like your).
