### ISSUE TITLE
Support `samsung` browser

### ISSUE THREAD

**Issue by evilebottnawi** [ai/browserslist#68]

**Comment by ai** [comment]
Do we have it in Can I Use?

**Comment by evilebottnawi** [comment]
@ai http://caniuse.com/#compare=samsung+4

**Comment by ai** [comment]
Awesome. Browserslist use Can I Use browsers. So we need only add it to docs. Do you want to send PR?

**Comment by evilebottnawi** [comment]
@ai yep :smile:
