### ISSUE TITLE
Use defaults but add support for a single browser

### ISSUE THREAD

**Issue by axelson** [ai/browserslist#70]
This may be relatively simple but I cannot find a matching example in the docs or previous issues. How do you keep everything default but mark a single browser to the list? I'm trying to add Mobile Safari on iOS 8.

**Comment by ai** [comment]
Sure, I will add `defaults`

**Comment by ai** [comment]
It is not urgent? I think I will add it only on next week.

**Comment by axelson** [comment]
Yeah it's not urgent since I can just use `> 1%, last 2 versions, Firefox ESR, otherbrowser > 1`

**Comment by ai** [comment]
Done 0b92a7b

**Comment by ai** [comment]
Released in 1.4.0

**Comment by axelson** [comment]
Great, thanks!

**Comment by ai** [comment]
Released in Autoprefixer 6.5.
