### ISSUE TITLE
Question: is there a way to automate custom stats fetching

### ISSUE THREAD

**Issue by jrencz** [ai/browserslist#71]
I see that JSON created using https://github.com/ai/browserslist#custom-usage-data is simple and can be created in CLI using Google Analytics API wrapper (for example with https://www.npmjs.com/package/ga-analytics) but I wonder whether there's a way you would suggest to use to automate the states fetching process?

**Comment by ai** [comment]
I don't know this way. Maybe you want to will develop it?

**Comment by jrencz** [comment]
@ai I'm thinking about it but not just yet: I'm currently helping to build MVP version of something that is probable to need a tool like this. If the team decides to automate that I'm willing to build it as open sourced.

**Comment by jrencz** [comment]
No luck here: the tool has been abandoned. In a foreseeable future I won't be able to work on this. I hope someone else will be willing to do it.
