### ISSUE TITLE
Is it possible to detect whether current browser matches given query in runtime?

### ISSUE THREAD

**Issue by dmzkrsk** [ai/browserslist#72]
E.g, I'd like to inform an user, that their browser doesn't fit in `'last 1 version, > 10%'`

**Comment by ai** [comment]
Hm. Interesting question. You could write `barowserslist-useragent` to generate CanIUse’s browser name by User Agent.

Di you want to develop this module?

**Comment by pastelsky** [comment]
There is a package for this now - https://github.com/pastelsky/browserlist-useragent

**Comment by williamboman** [comment]
@pastelsky Awesome, thanks!
