### ISSUE TITLE
ran into an error when using "not ie <= 7"

### ISSUE THREAD

**Issue by mobilesite** [ai/browserslist#73]
Hi, I've tried the config as followings several times for webpack and it seems just doesn't work for me, and there was no error threw out when i ran webpack. What does it mean by "not ie <= 7"?  I expect it to be all browsers except IE 6 and 7.  Looking forward to your reply.  Thank you!   

```
postcss: [ autoprefixer({ browsers: [
        'not ie <= 7'
] }) ]
```

**Comment by ai** [comment]
`not X` queries remove versions from left part of query.

Correct query for your choice: `> 0%, not ie <= 7`. But it will be *very bad* query. You really don’t need Chrome 5. With this query your CSS will contains completely outdated prefixes.

Use defaults query ;)
