### ISSUE TITLE
Another way to specify Custom Usage Data

### ISSUE THREAD

**Issue by Zmoki** [ai/browserslist#77]
Now we have two way to give Browserslist [Custom Usage Data](https://github.com/ai/browserslist#custom-usage-data):
- `stats` option
- `BROWSERSLIST_STATS` environment variable

I need more way and want to create Pull Request, but I need help to suggest.

What would be better?
- set Custom Usage Data at file with standard name (`browserslist-stats` for example) like `browserslist` file
- `use package.json`:

```
{
  ...
  "browserslist": {
    "stats": "./path_to_file"
  }
  ...
}
```

**Comment by ai** [comment]
Maybe we can specified it in `browserslist` config?

```
[stats]
big json
```

**Comment by ai** [comment]
or

```
[stats file]
path/to/file
```

**Comment by Zmoki** [comment]
I think, keep json in `browserslist` config file can be uncomfortable.

But `[stats file]` is fine!

**Comment by ai** [comment]
Sure. Let’s use `[stats]` for path.

But this fix will not be soon (I am working on HolyJS topic right now).

**Comment by ai** [comment]
`browserslist-stats.json` file support was added by @AleshaOleg in https://github.com/ai/browserslist/pull/86
