### ISSUE TITLE
Feature requests: Full exclude

### ISSUE THREAD

**Issue by MasterOfZozo** [ai/browserslist#81]
There is missing option to fully disable browser support.

**Comment by ai** [comment]
What do you mean? Could you show some examine?

**Comment by MasterOfZozo** [comment]
Currently we cannot write 'not ie' to exclude browser support instead of specific versions.
I am sorry, if it is not true, but in postcss autoprefixer throwing an error Unknown browser query `ie`

**Comment by ai** [comment]
Use `not ie > 0`.

We don’t have a shortcut, because I think it is a bad practice. You should not think about vendors, but think about popularity and other common parameters. IE users deserve Web too :D.
