### ISSUE TITLE
How to specify Android 2?

### ISSUE THREAD

**Issue by benfrain** [ai/browserslist#9]
I had been using this object to get prefixes for Android 2.3:

```
options: {
	browsers: ['last 2 version','Android 2']
},
```

However, as of latest Autoprefixer (5, via grunt-autoprefixer 2.2.0) this silently fails. What is the correct way to specify this browser with browserlist in Autoprefixer 5?

**Comment by ai** [comment]
```js
browsers: ['last 2 version', 'android 2.3', 'android 2.2', 'android 2.1']
```

**Comment by benfrain** [comment]
Excellent. Thanks.
