### ISSUE TITLE
Feature request: Target by coverage

### ISSUE THREAD

**Issue by AndyBarron** [ai/browserslist#90]
For example, I could specify that I wanted to target browsers that cover e.g. 90% of users, and we'd return a list covering browsers that combined cover >= 90%. (Probably a greedy algorithm where we keep adding the most used browsers until coverage hits or surpasses the target?)

Possible syntax: `coverage >= 90%`

**Comment by ai** [comment]
There is many way how we can combine browsers to fit 90%. I think this query is too tricky will make codebase and docs more complicated.

Do you have practice reason for it?

**Comment by AndyBarron** [comment]
Just a nice-to-have. Good point, though.

**Comment by Nettsentrisk** [comment]
Couldn't you just query with the percentage usage until you meet the desired coverage? With some clever math it shouldn't take that many queries to meet the threshold.

Eg. "coverage >= 90%" leads to querying "> 0.5%", that returns 85%, you query again ">0.25%", that returns 89%, you query again "> 0.2%", etc. until you cross the 90% threshold.

You are thus objectively picking the top browsers according to usage, until you meet the coverage requirement.

**Comment by ai** [comment]
`cover 90%` and `cover 90 % in US` was added by @Vasfed and released in 3.2
