### ISSUE TITLE
Feature request: Exclude desktop/mobile browsers

### ISSUE THREAD

**Issue by AndyBarron** [ai/browserslist#91]
If I wanted to support only desktop browsers, for example, it would be nice to use a normal query but add a directive to exclude mobile browsers (or vice versa).

Possible example syntax: `last 3 versions, desktop only`

**Comment by ai** [comment]
Sorry, I think it is a very bad practice and don't want to promote it by short query 😋

**Comment by AndyBarron** [comment]
FWIW, my use case is a WebGL game that would play terribly on mobile, but I
guess that's a fair point in general...

**Comment by ai** [comment]
Yeah, you can always use long query. I afraid about young developers, who could disable mobile browsers just because they have no media queries for them.

**Comment by g0t4** [comment]
If I'm building a desktop web app, one I don't intend to be used on mobile phones, nor tablets, then it seems logical to say "> 1%, desktop only" or something similar. 

Perhaps I would also want to say "desktop or tablet" 

Or, maybe I'm building a mobile only site and want to say "mobile only"

Why is this such a horrible thing to do?

And am I correct in assuming "long query" means to list out each browser and virtually create a "desktop only" criteria and then update that as new desktop browsers are introduced or removed?

**Comment by ai** [comment]
@g0t4 why it is impossible to visit your web app by mobile browser?

**Comment by g0t4** [comment]
Quite a few business apps are only designed for desktop use. It's not about being impossible, it's just that in these cases mobile doesn't matter. 

Just like sometimes a business only has US customers and so they care more about US market share as opposed to the rest of the world. In which case it's more likely that this app would include some IE support, whereas with international usage IE may not be important. 

The data source for caniuse.com (http://gs.statcounter.com/) tracks many interesting dimensions that are helpful to making decisions about what browsers to support, it might be nice to have more of these available in browserslist to avoid manual translation and periodic updates to criteria.

**Comment by g0t4** [comment]
I've also worked on apps that are only intended for mobile (tablets usually). So the opposite could be helpful too.

**Comment by ai** [comment]
@g0t4 do I understand correctly that there is no technical reason, why mobile users can't visit your website? So you just want remove mobile prefixes because you just don't care about your mobile users?

**Comment by g0t4** [comment]
Yes

-- 



----------
On Mon, Jul 31, 2017 at 7:16 PM, Andrey Sitnik <notifications@github.com>
wrote:

@g0t4 <https://github.com/g0t4> do I understand correctly that there is no
technical reason, why mobile users can't visit your website? So you just
want remove mobile prefixes because you just don't care about your mobile
users?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ai/browserslist/issues/91#issuecomment-319223132>, or mute
the thread

**Comment by ai** [comment]
@g0t4 this reason is exactly bad practice what I told about 😉.

A lot of poor people don't have desktop. They have only bad phones with UC Browser (because it save Internet).

I travel every 2 weeks and for that day I don't have access to my laptop. I have only phones.

Desktop-only feature is bad for humanity in general and for every phone user (including me) in practice.

So, my answer is still “no”. I became a developer to make the world a little better. Adding this desktop-only query will force developers to ignore people without desktops or people who have no desktop at this moment.

**Comment by thw0rted** [comment]
Just as a data point, I'm writing an application for use in a closed corporate environment, on an isolated network that has no mobile devices, and policy-managed browser deployments.  This is not an unusual case.

I agree that devs should generally consider mobile, and I espouse responsive design for general-purpose websites, but I have to disagree with the idea that desktop-only (or mobile-only, or tablet-only) is necessarily a bad pattern.

**Comment by ai** [comment]
@thw0rted yeap, there are rarely good cases (but even in your cases having mobile phone option is always good for company productivity, what if some developer is on the go?). For instance, kiosks.

But there are many more bad cases. I think adding a shortcut will bring more bad things to the ecosystem, than good things.

You can always create a sharable config like `extend browsers-config-desktop` with something like `not Android > 0, not ios > 0, …`

**Comment by davidjytang** [comment]
There are projects setup to separate the flow of mobile and desktop to 2 different sites.
Each site deal with only desktop or only mobile as the requirement and use case for mobile and desktop users can be vastly different. This is when the projects on each sites should use different browserslists.

Then there are mobile SPA projects that only needs mobile browsers. But as you said, one can simply write out the configs.

However by your reasoning to guide youngsters and make the world better place, maybe we should remove `dead` to help support all those poor devices, some people are stuck with old devices and old browsers? or may we should always force `Firefox` tag to foster open web? As you can see, there are many ways to make the world better. Not being able to succinctly specify project requirement is just a nuance.

Your effort on this is appreciated. By providing mobile tag will not **force** developer to ignore desktop as it is their choice. Thanks again on your effort.

**Comment by ai** [comment]
> There are projects setup to separate the flow of mobile and desktop to 2 different sites

It is bad practice because it will force users to learn two different UI and in practice developer will forget to add the same 100% features to both websites, so users will need to use “Show desktop version” feature on mobile browsers.

> However by your reasoning to guide youngsters and make the world better place, maybe we should remove dead to help support all those poor devices

`dead` is not old browsers. It is browsers without security updates. We decided that force users to avoid insecure browsers is a good compromise.

> By providing mobile tag will not force developer to ignore desktop as it is their choice

I think that having a simple query to ignore mobile browsers will force them to think that it is a good practice.

**Comment by davidjytang** [comment]
Not trying to convince you to change your decision. Merely to point out there are scenarios beyond your described world.

Now there is a big assumption on your part that *any project at all should make serving desktop a requirement* and *any project at all should also make serving mobile as a requirement*, which is simply not the case in corporate apps.

> It is bad practice because it will force users to learn two different UI and in practice developer will forget to add the same 100% features to both websites, so users will need to use “Show desktop version” feature on mobile browsers.

In this case, you are assuming teams never apply UI guideline among different projects.
Also you are assuming mobile project requirement are always the same as desktop project requirement.

> I think that having a simple query to ignore mobile browsers will force them to think that it is a good practice.

I see what you mean. I think you meant to say it will **imply** that it is a good practice. Well, this point might be subjective. If you are up to driving convention over configuration, I think you are already successfully doing that with the `default` rule. The rest of the configuration may be left to the users of this tool.

**Comment by ai** [comment]
I understand that there is a cases, when you may really do not need a mobile browsers. But I think:

1. These cases are rare
2. There is still solution for this cases. It will just make Browserslist bigger, but will work.
3. Benefits of making Browserslist config smaller for these rare teams will be lower, than negative effects of promoting mobile browsers avoiding for a wrong cases.

**Comment by davidjytang** [comment]
As someone in a company makes internal websites for corporate, I can hardly argue for the case being rare.

Other than that, I agree with you and thank you for your good work.

**Comment by MilesBHuff** [comment]
At the company where I work, my team has one site that only supports mobile, and one that only supports desktop.  Being able to exclude one or the other would be a helpful way to reduce bundle size.
You say you're not adding the feature because it would make the World a worse place; but you're arguing that from a place of theory, where right now there are many real-world situations in which this feature would make the World an objectively better place.

**Comment by thw0rted** [comment]
Miles, if you read up about 2 pages, you'll see that "`not Android >0, not ios >0`" is supposed to basically do what the original issue asked for.  It's very slightly less convenient than `not mobile` but probably covers everybody's use cases.

**Comment by MilesBHuff** [comment]
> Miles, if you read up about 2 pages, you'll see that "`not Android >0, not ios >0`" is supposed to basically do what the original issue asked for. It's very slightly less convenient than `not mobile` but probably covers everybody's use cases.

Unfortunately, this is not a true catch-all.  To exclude every mobile browser, you have to do something like this:
```
not bb      >= 0
not and_chr >= 0
not and_ff  >= 0
not and_qq  >= 0
not and_uc  >= 0
not android >= 0
not ios_saf >= 0
not op_mini all
not op_mob  >= 0
```
And you have to add new mobile browsers to it as they become available.  This is obviously not a great solution, and there should be something in browserslist that lets you specify all of these with a simple keyword:  `mobile`.

**Comment by thw0rted** [comment]
IMHO that's a good enough reason to re-open the request.  @ai if you're still eyes-on, would you consider that?

Again, put a big red banner in the docs (or don't list it at all!), forcibly log a warning on the console if you want, call the keyword `really_exclude_mobile_yes_I_understand_why` if you like.  I agree that "junior devs" should be discouraged from throwing it in there to lazily avoid supporting mobile, in the strongest possible terms, but, also, the entire point of `browserslist` is to accurately describe what environments we as application developers do or do not want to support.  As I stated above, you may not have personal experience with them, but there are a significant number of valid use cases where pages simply cannot be loaded on a mobile client.  Those applications should be accurate described in their build metadata as such.

**Comment by ai** [comment]
I still think that long list of queries like `not bb      >= 0` works good enough for this rare case.

We do not need a good solution for every possible use case. Good use cases to avoid mobile browsers are very rare.

**Comment by MilesBHuff** [comment]
This isn't rare, though.  Not at all.  Just make it so browserslist will throw a warning or something if you try to use the feature, or add some other barrier to using it.  But there should absolutely be `mobile` and `desktop` options -- browserslist is supposed to accurately describe what environments an application is designed to support.  Our desktop-only site doesn't even have mobile styling -- it's unusable on phones.  It's only supposed to be used on desktop computers at car dealerships.
