### ISSUE TITLE
Errors when using different environments

### ISSUE THREAD

**Issue by ivancuric** [ai/browserslist#92]
Calling `browserslist()` from `const browserslist = require('browserslist');` gives the following error, when using this config:
```
[production]
last 2 version

[development]
last 1 Chrome version
```
`BrowserslistError: Unknown browser query [production]`

`process.env.NODE_ENV` gives out the proper environment variable tho. Any ideas?

**Comment by ai** [comment]
@ivancuric do you use `browserslist` from GitHub master via `"browserslist": "ai/browserslist"` or just latest released from npm?

I am making a new version and right now docs in `master` have few unreleased features.

Sorry, I should use a branch for it, but I forgot and now it is too late (anyway release will be tomorrow).

**Comment by ivancuric** [comment]
Just the latest npm one. Guess I'll wait :D
