### ISSUE TITLE
Readme package.json wrong brackets {} -> []

### ISSUE THREAD

**Issue by Anima-t3d** [ai/browserslist#94]
The readme says:

> {
  "private": true,
  "dependencies": {
    "autoprefixer": "^6.5.4"
  },
  "browserslist": {
    "> 1%",
    "last 2 versions"
  }
}

But it should be (Note the part **"browserslist": {** vs **"browserslist": [**):

> {
    "private": true,
    "dependencies": {
      "autoprefixer": "^6.5.4"
    },
    "browserslist": [
      "> 1%",
      "last 2 versions"
    ]
}

**Comment by ai** [comment]
Thanks. I fixed it used your name: b603889
