### ISSUE TITLE
Add electron-to-chrome mapping

### ISSUE THREAD

**Issue by Kilian** [ai/browserslist#96]
I'd propose adding an [Electron](https://electron.atom.io) mapping to Browserslist. Electron is a popular build target, and Electron versions map to specific chrome versions. Babel-preset-env keeps a list of this mapping: https://github.com/babel/babel-preset-env/blob/master/data/electron-to-chromium.js 

Name would be "Electron", and "last 2 Electron versions" would map to "Chrome 53-53" for example.

**Comment by ai** [comment]
We need separated source of Electron → Chrome mappings. `babel-preset-env` depends on `browserslist`, so we will have circular dependency.

@baer @hzoo are you OK to move it to separated library?

**Comment by ai** [comment]
Maybe we could get some official mapping package from Electron community?

@zeke @kevinsawicki what do you think guys?

**Comment by Kilian** [comment]
They keep one here: https://github.com/electron/electron.atom.io/blob/gh-pages/_data/versions.json which has full versions of chrome. Seems like a nicer option indeed.

**Comment by ai** [comment]
@Kilian yeap, that config is more official. But I need some npm package. Also it is good idea to keep file size small at least in special version for Browserslist.

Do you want to create and maintain npm package if @zeke @kevinsawicki will ignore us?

**Comment by Kilian** [comment]
absolutely, though I think there's place for one in the electron repository.

**Comment by zeke** [comment]
The canonical home of that Electron versions data is https://atom.io/download/electron/index.json

That URL will not change, and It is automatically updated with every Electron release.

Feel free to create an npm package that contains this data.

**Comment by ai** [comment]
@Kilian OK, I am waiting for your package :).

I recommend to you have a script to update package very fast — only on easy update you will always have power to support it :D.

**Comment by Kilian** [comment]
Shall I keep with the https://github.com/babel/babel-preset-env/blob/master/data/electron-to-chromium.js format so that babel-preset-env can also use it? (With the value being the full version instead of the main version)

**Comment by ai** [comment]
@Kilian I think so. I like it because it is very compact.

**Comment by Kilian** [comment]
Got the script + result in this repository: https://github.com/Kilian/electron-to-chromium/ If this is OK, I'll make the NPM Package! :)

**Comment by ai** [comment]
Looks nice. Also what do you think about this usage:

```
browserslist(electronToChrone("1.4"))
```

In this case you need also helper with browserslist compatible output.

I try to reduce liberty size to use it on client side, so extra data package with rare usage is not best option.

**Comment by Kilian** [comment]
Are you proposing to keep support for Electron mapping outside of browserlist? So instead of doing an "Electron > 1.3" query from right inside browserlist, you'd do an electronToChrome("Electron >= 1.4") function call and it would return a "Chrome >= 53" string?

Would you expect just "53" for the fully qualified "1.4.14", or would you then expect "Chrome >= 53.0.2785.143" ?

**Comment by ai** [comment]
Only `chrome 53`.

My idea is start from this helper API (with a link from Browserslist docs). And move it to core if it become popular.

**Comment by Kilian** [comment]
I now have the following: https://github.com/Kilian/electron-to-chromium/blob/master/index.js

* a simplified list
* a full list
* a simple version-to-version mapping
* a browserlist specific version-to-version mapping

Is the latter one something you can work with? I'll update both to work with the full version list as well.

**Comment by ai** [comment]
Looks good. After a release, please send a PR to Browserlist docs. I think “Browsers” section is best option.

**Comment by Kilian** [comment]
Published here: https://www.npmjs.com/package/electron-to-chromium. PR incoming!

**Comment by amilajack** [comment]
So does this mean that something like this wont work:



```
```

**Comment by ai** [comment]
@amilajack nope :(. But if we will see that users use it, I will add electron to core.

**Comment by Kilian** [comment]
So, not yet is the hopeful answer :)

**Comment by amilajack** [comment]
>  But if we will see that users use it, I will add electron to core.

@ai I'm a core maintainer of [chentsulin/electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate). If it is added to core, i will definitely add it

**Comment by ai** [comment]
Done 2c902aea5bda164215d72244ef5daad67b29d470

**Comment by ai** [comment]
@amilajack but you need to add `browserslist` key to `package.json` or `browserslist` config ;)

**Comment by ai** [comment]
Released in 1.6

**Comment by amilajack** [comment]
Made a PR for this 🎉 https://github.com/chentsulin/electron-react-boilerplate/pull/665

Unfortunately, I had trouble adding autoprefixer support with postcss-loader.

**Comment by richardgoater** [comment]
I think this has caused the world to download electron? I just got pinged at work because the Squirrel installer in [this repo](https://github.com/electron/windows-installer/tree/main/vendor) was flagged as malware. Package management gone very wrong.
